### ISSUE TITLE
clarify licensing

### ISSUE THREAD

**Issue by adrelanos** [GrapheneOS/os_issue_tracker#109]
I've looked at some random repositories.

https://github.com/GrapheneOS/platform_build
https://github.com/GrapheneOS/kernel_google_marlin
https://github.com/GrapheneOS/platform_bionic
https://github.com/GrapheneOS/branding_extra

Wondering about licensing. https://grapheneos.org/source does not answer that either.

Could you please clarify what license the repos are under?

Ideally, could you please add either a LICENSING and/or COPYING file to each repository?

Btw https://www.privacytools.io/operating-systems/ lists GrapheneOS as "contrib".

> This software may depend on or recommend non-free software.

So would be good to clarify.

**Comment by thestinger** [comment]
https://github.com/GrapheneOS/branding_extra is not part of GrapheneOS.

https://github.com/GrapheneOS/platform_build, https://github.com/GrapheneOS/kernel_google_marlin and https://github.com/GrapheneOS/platform_bionic are all forks of upstream repositories and have clear licensing. I don't see what's unclear about the licensing.

> Wondering about licensing. https://grapheneos.org/source does not answer that either.

I don't know what's unclear. It's an open source project with permissive licensing. You can see the licensing for the repositories already, including the ones you linked.

> Ideally, could you please add either a LICENSING and/or COPYING file to each repository?

I already do this for my own repositories. I don't need to do it for forks of upstream repositories. GrapheneOS code is available under the same licensing for those repositories. The licensing for the Android Open Source Project is not unclear. You may not understand the conventions or how it's marked, but it's being done.

> This software may depend on or recommend non-free software.

As a portable operating system, it doesn't depend on closed source software and it doesn't recommend it. Many of the targeted devices will depend on closed source firmware and libraries. Those are part of the base operating system but rather it's device-specific code. GrapheneOS is certainly going to ship full security updates.

> So would be good to clarify.

Misinformation and spin spread by other people isn't my responsibility.

**Comment by thestinger** [comment]
https://github.com/GrapheneOS/branding_extra is not part of GrapheneOS.

https://github.com/GrapheneOS/platform_build, https://github.com/GrapheneOS/kernel_google_marlin and https://github.com/GrapheneOS/platform_bionic are all forks of upstream repositories and have clear licensing. I don't see what's unclear about the licensing.

> Wondering about licensing. https://grapheneos.org/source does not answer that either.

I don't know what's unclear. It's an open source project with permissive licensing. You can see the licensing for the repositories already, including the ones you linked.

> Ideally, could you please add either a LICENSING and/or COPYING file to each repository?

I already do this for my own repositories. I don't need to do it for forks of upstream repositories. GrapheneOS code is available under the same licensing for those repositories. The licensing for the Android Open Source Project is not unclear. You may not understand the conventions or how it's marked, but it's being done.

> This software may depend on or recommend non-free software.

As a portable operating system, it doesn't depend on closed source software and it doesn't recommend it. Many of the targeted devices will depend on closed source firmware and libraries. Those are part of the base operating system but rather it's device-specific code. GrapheneOS is certainly going to ship full security updates.

> So would be good to clarify.

Misinformation and spin spread by other people isn't my responsibility.

**Comment by thestinger** [comment]
https://github.com/GrapheneOS/branding_extra is not part of GrapheneOS.

https://github.com/GrapheneOS/platform_build, https://github.com/GrapheneOS/kernel_google_marlin and https://github.com/GrapheneOS/platform_bionic are all forks of upstream repositories and have clear licensing. I don't see what's unclear about the licensing.

> Wondering about licensing. https://grapheneos.org/source does not answer that either.

I don't know what's unclear. It's an open source project with permissive licensing. You can see the licensing for the repositories already, including the ones you linked.

> Ideally, could you please add either a LICENSING and/or COPYING file to each repository?

I already do this for my own repositories. I don't need to do it for forks of upstream repositories. GrapheneOS code is available under the same licensing for those repositories. The licensing for the Android Open Source Project is not unclear. You may not understand the conventions or how it's marked, but it's being done.

> This software may depend on or recommend non-free software.

As a portable operating system, it doesn't depend on closed source software and it doesn't recommend it. Many of the targeted devices will depend on closed source firmware and libraries. Those aren't part of the base operating system but rather it's device-specific code. GrapheneOS is certainly going to ship full security updates.

> So would be good to clarify.

Misinformation and spin spread by other people isn't my responsibility.

**Comment by thestinger** [comment]
https://github.com/GrapheneOS/branding_extra is not part of GrapheneOS.

https://github.com/GrapheneOS/platform_build, https://github.com/GrapheneOS/kernel_google_marlin and https://github.com/GrapheneOS/platform_bionic are all forks of upstream repositories and have clear licensing. I don't see what's unclear about the licensing.

> Wondering about licensing. https://grapheneos.org/source does not answer that either.

I don't know what's unclear. It's an open source project with permissive licensing. You can see the licensing for the repositories already, including the ones you linked.

> Ideally, could you please add either a LICENSING and/or COPYING file to each repository?

I already do this for my own repositories. I don't need to do it for forks of upstream repositories. GrapheneOS code is available under the same licensing for those repositories. The licensing for the Android Open Source Project is not unclear. You may not understand the conventions or how it's marked, but it's being done.

> This software may depend on or recommend non-free software.

As a portable operating system, it doesn't depend on closed source software and it doesn't recommend it. Every potential target device depends on closed source firmware. GrapheneOS is certainly going to ship full security updates. Most devices also have closed-source driver libraries / services. This is not part of the base OS and is not included in a checkout of GrapheneOS. None of this is part of the portable OS and it isn't needed for the generic targets. It's something tied to the devices, not GrapheneOS in particular.

> So would be good to clarify.

Misinformation and spin spread by other people isn't my responsibility.

**Comment by thestinger** [comment]
https://github.com/GrapheneOS/branding_extra is not part of GrapheneOS.

https://github.com/GrapheneOS/platform_build, https://github.com/GrapheneOS/kernel_google_marlin and https://github.com/GrapheneOS/platform_bionic are all forks of upstream repositories and have clear licensing. I don't see what's unclear about the licensing.

> Wondering about licensing. https://grapheneos.org/source does not answer that either.

I don't know what's unclear. It's an open source project with permissive licensing. You can see the licensing for the repositories already, including the ones you linked.

> Ideally, could you please add either a LICENSING and/or COPYING file to each repository?

I already do this for my own repositories. I don't need to do it for forks of upstream repositories. GrapheneOS code is available under the same licensing for those repositories. The licensing for the Android Open Source Project is not unclear. You may not understand the conventions or how it's marked, but it's being done.

> This software may depend on or recommend non-free software.

As a portable operating system, it doesn't depend on closed source software and it doesn't recommend it. Every potential target device depends on closed source firmware. GrapheneOS is certainly going to ship full security updates. Most devices also have closed-source driver libraries / services. This is not part of the base OS and is not included in a checkout of GrapheneOS. None of this is part of the portable OS and it isn't needed for the generic targets. It's something tied to the devices, not GrapheneOS in particular.

> So would be good to clarify.

Misinformation and spin spread by other people isn't my responsibility. If they want to encourage using insecure operating systems including those not shipping full security updates, the harm they're causing is on them. The same goes for spreading spin and attacks on how GrapheneOS approaches it. Dishonest, unethical people aren't something I can correct. The page you're linking does not say this for Debian and Arch Linux despite them shipping closed source software and firmware in their official repositories and/or base OS. Also, whether or not the OS is shipping the updates for it, which are crucial for security, closed source software is present on every computing device in practice. Architectures like x86 and ARM are inherently proprietary and have a ton of closed source firmware and microcode in addition to the hardware itself being massively complex and not open source. The same applies to nearly every component: GPU, Wi-Fi, etc. I don't understand the need for people to bother me about this in particular. It's not my fault or choice.

**Comment by thestinger** [comment]
This https://github.com/GrapheneOS/os_issue_tracker repository is only for the repositories in https://github.com/GrapheneOS/platform_manifest that aren't standalone projects with their own https://github.com/GrapheneOS/hardened_malloc. Only the integration of those standalone projects into the OS is covered by this issue tracker.

Repositories like https://github.com/GrapheneOS/branding_extra aren't covered by this tracker because they aren't part of the OS. In the past, I used to split the organization into one for everything referenced by platform_manifest and another for everything else but I'm no longer interested in doing that. Repositories like https://github.com/GrapheneOS/hardened_malloc are both a standalone project and referenced in the manifest to include them in the OS source tree and build them with it. I'm using the https://github.com/GrapheneOS organization to represent GrapheneOS as an organization, not a namespace for the OS source tree in particular, so it contains a lot of other things. I have a separate archive organization https://github.com/GrapheneOS-Archive to avoid clutter as an alternative to simply deleting repositories that are no longer used which would break the old manifest tags. The https://github.com/AndroidHardeningArchive organization is a very incomplete archive of past work that has not yet been ported to GrapheneOS. Lots of this work is only available via older tags there, since the resources to port it forward aren't available.

There's currently no GrapheneOS artwork included in the OS. There isn't even a real boot animation, just "GrapheneOS" in Roboto Condensed rendered via the standard gradient animation used when an actual boot animation isn't available. There's not yet a custom default wallpaper and all the icons are the usual standard permissively licensed ones. The intention is for this to change, but the project has extremely limited resources and they aren't being spent on branding and making artwork. This stuff isn't software so the license will have little to do with whether the software is open source / free software, and it wouldn't be appropriate for usage elsewhere anyway since it will use the GrapheneOS branding. This is getting into trademark law rather than copyright law. It wouldn't be acceptable for someone to present something as GrapheneOS that is not actually GrapheneOS. If someone makes a derivative of the OS, I expect them to use their own name and branding. There's a different between an OS based on GrapheneOS and GrapheneOS itself.

Similarly, GrapheneOS is not literally the Android Open Source Project but rather based on it. GrapheneOS is explicitly not Android, because it deliberately doesn't conform to the Compatibility Definition Document and Compatibility Test Suite requirements for considering an OS to be part of the Android family. It's entirely possible to make an OS with an entirely different kernel and software stack that's allowed to be referred to as Android as long as it is fully meets the compatibility and other requirements. Those are the rules for using the trademark. I make *fair use* of that trademark by referring to GrapheneOS as being almost entirely fully compatible with Android apps. It's not *entirely* compatible though since it deliberately makes restrictions for privacy/security that are not permitted by the CDD / CTS. The Android Open Source Project is entirely open source and is permissively licensed other than some GPL2 components like the Linux kernel, OpenJDK libraries (more permissive licensing than plain GPL2) and portions of the toolchain used to build it. However, that doesn't mean I can refer to GrapheneOS as literally being Android since it's not a matter of copyright law / software licenses.

**Comment by adrelanos** [comment]
Btw I have no idea about privacytools.io except a contributor recently pointed me at that issue and created a ticket https://github.com/privacytoolsIO/privacytools.io/issues/1144 for it which they quickly resolved.
