### ISSUE TITLE
[Feature request] Display on how many times the application accessed the permission x

### ISSUE THREAD

**Issue by k3tju** [GrapheneOS/os_issue_tracker#111]
For each app, LineageOS has a display on how many times the application accessed the permission x (ex: Location, Contacts, etc...)
That would be a nice feature for the user to know if an application seems to be abusing a certain permission if this is in the scope of the project.

**Comment by thestinger** [comment]
> That would be a nice feature for the user to know if an application seems to be abusing a certain permission if this is in the scope of the project.

I don't see how it provides that and I don't think it's something I'm interested in providing since it's misleading and leads users down the wrong path about thinking about these things. The stats you're referring to are from AppOps and don't correspond to a user-facing concept of using a permission like Location like fetching the current location. You need to file a more specific issue for a permission where this makes sense, explain why the existing functionality is not enough (i.e. requesting permissions, toggling them, disallowing various things in the background and showing a log of recent location accesses), etc. This is too vague and the answer to whether I want a similar misleading, poorly done implementation like LineageOS is no. I don't want misleading features / frills. I want real privacy and security features with a clear purpose. Monitoring permission usage may be useful but not like this.

**Comment by thestinger** [comment]
You need to file issues like this in a way that's much more specific, with a sensible design and a justification for it. Asking to copy poorly done features from other projects that were implemented the way they were based on existing inadequate code in AOSP just isn't going to go anywhere. In general, the project is looking for work on the existing features, not requests for more features that no one is working to implement.
