### ISSUE TITLE
[Bug] Grapheneos work profile doesn't have network access (test with this with Shelter app)

### ISSUE THREAD

**Issue by k3tju** [GrapheneOS/os_issue_tracker#113]
I installed Shelter (https://f-droid.org/en/packages/net.typeblog.shelter) and tested it. Everything seems to work with GrapheneOS except the network access for the work profile. I noticed a few bugs on duplicated apps but I did not find those critical and usually, reinstalling the app helped.

Can somebody try this as well and confirm this bug?

This feature is very helpful if you need to install non F-Droid apps. This can be the case, for example, if your employer requires a certain app for work.
It is an excellent feature because you can choose the timing during which your work profile is running and all apps are isolated from your main profile by the OS.

**Comment by SimonBrazell** [comment]
@k3tju I have been doing some testing with Shelter myself and noticed an issue last night with the built-in webview that I was able to resolve. It seems Shelter doesn't copy the Vanadium browser across to the Work Profile which means that any app that uses the system 'webview' (in-app browser) cannot access it, for me the built-in Email app was crashing whenever I attempted to access any emails. I discovered this by observing the system logs via `adb logcat` seeing Webview exceptions.

The fix is to simply copy the Vanadium browser across to the Work Profile, please try this and let me know if it resolves your issues. I don't believe this is an issue with GrapheneOS specifically.

**Comment by thestinger** [comment]
I don't think any of these issues are GrapheneOS problems but rather Shelter issues.

**Comment by bungabunga** [comment]
The app was upgraded recently and it works on the latest GrapheneOS beta (with few small glitches).
