### ISSUE TITLE
[Feature request] Possibility to permanently allow a certain app to manage Bluetooth or wifi

### ISSUE THREAD

**Issue by k3tju** [GrapheneOS/os_issue_tracker#115]
In the last years, I was using Smarter wifi from Fdroid to remember where to switch on wifi according to cell towers aggregation. This gives a rough estimate of a location in most countries. The android system itself has a function for automatic wifi management but it can only turn it off and not turn it back on. That's a problem when I get home for instance. Another app that is similar to smarter wifi but less advanced is Wifi automatic (also from FDroid)

Without a function that allows permanently a certain app to manage Bluetooth or wifi, such apps cannot operate properly because you are not looking at your phone all the time while they operate so you cannot confirm the access.

This design pattern forces people to keep their Wifi ON and facilitates tracking + reduces battery life so having a tick box to permanently allow an app to use it at the first permission prompt would be a great improvement.

**Comment by beerisgood** [comment]
As I know this is possible with stock Google ROMs or with such apps which need GPS

Dont see a reason to include such feature in GrapheneOS. Most users doesn't need that

**Comment by thestinger** [comment]
There's already a "Turn on Wi-Fi automatically" setting in the Wi-Fi preferences.

This also doesn't fall into the privacy and security scope of GrapheneOS.

> This design pattern forces people to keep their Wifi ON

I don't see how.

> facilitates tracking

It doesn't. The Wi-Fi firmware / driver use anonymous scanning with minimal probe requests, randomized probe sequence numbers and randomized MAC addresses. This is standard upstream for Pixels and probably many other devices using Qualcomm Atheros Wi-Fi rather than Broadcom Wi-Fi.

**Comment by k3tju** [comment]
Hello!
My bad. It can turn ON but for me it never turns OFF automatically.
Thank you for the info on the Qualcomm Atheros @thestinger . Was mislead me on that was that the "Wi-Fi MAC address" was always correct in the "About phone" section.

**Comment by thestinger** [comment]
Scanning MAC randomization and associated MAC randomization are different things. Associated MAC randomization is currently opt-in and becomes the default in Android Q. GrapheneOS used to have a custom implementation but like many other features it was left out of the revival of the project due to the pending inclusion upstream in Android Q. You need to look at what Android Q will be providing as part of the baseline and what GrapheneOS has provided in the past.
