### ISSUE TITLE
[Privacy-Question] Network location provider in use. Google?

### ISSUE THREAD

**Issue by k3tju** [GrapheneOS/os_issue_tracker#117]
What is the current Wifi network location provider? Is it Google?
If it is, how hard would it be to replaced, or give the option to use Mozilla or WiGLE? Like what you can do with MicroG.

**Comment by thestinger** [comment]
There's no network-based location provider beyond the baseline cellular network functionality. I don't want that in GrapheneOS. There's already https://github.com/GrapheneOS/os_issue_tracker/issues/24 filed about eventually having a robust implementation of supplementary location information but it's a low priority and people from the community would also need to step up and start doing some work on these features for them to ever be implemented. In general, nearly everything that's wanted in the short / mid term is already filed. Long term plans are not currently filed as issues here since it's not as actionable and I don't want non-actionable or overly ambiguous issues filed here.

> Like what you can do with MicroG.

This isn't designed in a privacy / security focused way that would be appropriate for GrapheneOS.

**Comment by renlord** [comment]
Alternatively, instead of sending network cell ID to a 3rd-party service provider that returns geolocation data, would it be appropriate if a local dataset containing CellID locations (i.e. from https://www.opencellid.org) be stored locally and the newly built network location provider can just look up locally to provide location through the FusedLocation service?

Location functionallity is quite crippled at the moment without a low-battery location API.

**Comment by thestinger** [comment]
That's what https://github.com/GrapheneOS/os_issue_tracker/issues/24 is filed about.
