### ISSUE TITLE
[Security-Question] What about ATtention Spanned? - atcommands.org

### ISSUE THREAD

**Issue by k3tju** [GrapheneOS/os_issue_tracker#118]
Is this type of attack: https://atcommands.org/ possible on GrapheneOS?
That is important to know because some of us might travel in countries without human rights and targeting human right activists. In some locations, you might be required to handle your phone to threat actors.

**Comment by thestinger** [comment]
No, it's not possible, because it targets hardware without these blatant vulnerabilities. See https://grapheneos.org/#device-support. Hardware and firmware are very important parts of security. GrapheneOS targets hardware with full security support and robust low-level security including an isolated baseband, debugging functionality like this outright disabled or allowed only when the bootloader is unlocked, full verified boot and many other hardware/firmware-based security features. The difference between decent hardware targets and poor ones is far more substantial than the difference between GrapheneOS and AOSP.

**Comment by thestinger** [comment]
Please ask questions either on the subreddit (https://reddit.com/r/GrapheneOS) or the IRC / Matrix channel (#grapheneos on Freenode or #grapheneos:matrix.org) in the future. The issue tracker is only for filing bugs, and in rare cases feature requests will also be accepted when they align with the goals of the project and are concrete, actionable issues with a design plan.
