### ISSUE TITLE
No Notification Sounds Available

### ISSUE THREAD

**Issue by sempervictus** [GrapheneOS/os_issue_tracker#143]
Using a pixel 3XL, the recent update scrambled all ring/alarm/notification tones. After trying to set them back, all possible options for which tones to use vanished, the currently selected tones are represented numerically, and the there is no ring tone selected for calls and none available to select, so the phone is now on permanent mute. Permissions issue?

**Comment by thestinger** [comment]
Have you rebooted since updating?

**Comment by beerisgood** [comment]
Just select your ringtone and done

**Comment by sempervictus** [comment]
I have rebooted, and there are no ringtones available from which I can select anything.

**Comment by thestinger** [comment]
@sempervictus Lots of people ran into an issue with this but it was fixed for everyone else after the first reboot triggered another data migration. I'm unsure why this is still an issue for you. It's tied to the Android 9 -> Android 10 migration, and at least for everyone else the issue was just that the data format migration wasn't completed one the initial reboot as it was supposed to be.

**Comment by thestinger** [comment]
@sempervictus Lots of people ran into an issue with this but it was fixed for everyone else after the first reboot triggered another data migration. I'm unsure why this is still an issue for you. It's tied to the Android 9 -> Android 10 migration, and at least for everyone else the issue was just that the data format migration wasn't completed after the initial reboot as it was supposed to be.

**Comment by sempervictus** [comment]
A few reboots later this seems resolved. Odd, and thanks for clarifying what was going on.

**Comment by beerisgood** [comment]
Please re-open, the problem still exist.

Often, at random times my alarm/ notification sounds are gone and if i go to settings, only numerically are listed and the list with default sounds is empty.

Only a reboot help but sadly don't fix it after some random time.
This is a very important issue, as alarm without sound is big problem if you need to wake up.

Also as written on the screen, the funny think is that my personal calling sound doesn't go away

![ringtones](https://user-images.githubusercontent.com/9625159/72217767-a4eb3d00-352a-11ea-99ef-7cd779cc6293.jpg)

**Comment by sempervictus** [comment]
This does come back every update or two, a subsequent reboot appears to permit the user to set their sounds again, does need manual effort each time though.

**Comment by beerisgood** [comment]
@sempervictus you should re-open this issue

**Comment by Finn10111** [comment]
Yes, I am also facing this issue. I did a clean install a few days ago on my new Pixel 3a.

**Comment by raccoonia** [comment]
I am seeing the same issue on a Pixel 3a running QQ2A.200405.005.2020.04.14.23

After a reboot the system sees all ringtones, after some time (random) and several phonecalls later I notice my ringtone changes to a different one. Just like in the screenshots of @beerisgood there are no ringtone names, only numbers.
A reboot fixes the issue temporarily only

Is there a way to extract the ringtones from the system to manually add them? Manually added ringtones do not seem to be affected.

**Comment by thestinger** [comment]
File a new issue.

**Comment by beerisgood** [comment]
For some reason I doesn't had the problem since month or 2.

I don't change my setup but clean alarm clock settings. Maybe that did the fix as my clock doesn't work in past.
