### ISSUE TITLE
Chat bubbles in Android 13 appear on screen of other users

### ISSUE THREAD

**Issue by ph00lt0** [GrapheneOS/os_issue_tracker#1447]
I am seeing chat bubbles from Signal app in a different user profile. I can open them but unable to read further contents, so its not useful and rather confusing. Interestingly they do show user profile pictures.

**Comment by tyler-reclen** [comment]
I also have this bug. 

Signal is installed on the main user and I have "chat bubbles" and " send  notifications to current user" both enabled

Since the android 13 update whenever signal sends a notification and I am on another user a bubble pops up with the contact photo and a momentary preview of the message content. The bubble can be "opened" and "closed" freely but shows a semi-transparent blank page rather than the conversation.

 Are there any tests I can do to be helpful in narrowing down this bug?

**Comment by SurienDG** [comment]
Experiencing same issue for other apps not just Signal [Pixel 6]

**Comment by thestinger** [comment]
Upstream issue.
