### ISSUE TITLE
Question: Why Vanadium?

### ISSUE THREAD

**Issue by stfnhh** [GrapheneOS/os_issue_tracker#152]
Why does GrapheneOS use Vanadium, why not use Bromite and Bromite SystemWebView instead?  They both have similar goals and features, it'd be one less thing to worry about.

**Comment by thestinger** [comment]
The bug tracker isn't an appropriate place for questions. You should ask them on the subreddit or IRC / Matrix channel.

Bromite doesn't directly fit the needs of GrapheneOS and would not be one less thing to worry about. It would need to be forked for GrapheneOS with all the unwanted patches dropped, patches that are not quite ready for the requirements / standards of GrapheneOS dropped, the missing changes from Vanadium would need to be added and it would need to be further changed from there as Vanadium development continues. It's going to end up identical to Vanadium anyway, so why bother forking it?

**Comment by thestinger** [comment]
If there's a feature in Bromite that's appropriate for Vanadium, the patch can be added. In general, if one of those patches has not been added to Vanadium, there's a good reason for it. The goals, approach and standards for the changes are different and using Bromite is not a viable option. If you're interested in adding some of the changes from Bromite to Vanadium, that's something you're welcome to work on. There will need to be changes made or they'd have already been applied.

In general, if you aren't already deep into working on GrapheneOS, you're not in a position to give any helpful advice or suggestions. Most things are the way that they are after years of working on it and arriving at conclusions about how they should be approached based on the knowledge / experience gained from that. The project doesn't really have that much to show for the enormous amount of work that has gone into it aside from lots of knowledge and experience, due to the need to keep porting the features forward and the lack of resources to get that done.
