### ISSUE TITLE
seedvault is resetting vpn app when backing up

### ISSUE THREAD

**Issue by h2dden** [GrapheneOS/os_issue_tracker#194]
I performed a backup with seedvault and during the process I noticed that several apps are resetted: first conversations - all account get disconnected but then these are reconnected, nit much of an issue.
But, RiseupVPN is completely shut down and does not restarts/reconnects, basically the internet connection is blocked.
There is no warning, no message.
Further, upon finishing the backup, a message is shown in notifications saying 0 apps were not backed up (or something like that). But, upon checking the apps status, there arw a lot of apps marked in red: which I assumed were not backed up (apps and/or respective data).
Also, selecting apps to exclude from backup is not persistent: after a backup all apps are selected again...

**Comment by thestinger** [comment]
You should know that Seedvault is using Android's standard backup infrastructure and most of what you're talking about is simply how this standard backup infrastructure works. Many apps have poor support for it even though most apps can fully support it by simply not doing anything like disabling support for backups.

> I performed a backup with seedvault and during the process I noticed that several apps are resetted: first conversations - all account get disconnected but then these are reconnected, nit much of an issue.
> But, RiseupVPN is completely shut down and does not restarts/reconnects, basically the internet connection is blocked.
> There is no warning, no message.

The backup process has to temporarily halt the apps. If they don't handle it properly, the apps are buggy. Seedvault uses the standard Android backup infrastructure and apps are expected to be compatible with it. If apps can't handle this properly, there are other situations they also won't handle properly.

> Further, upon finishing the backup, a message is shown in notifications saying 0 apps were not backed up (or something like that). But, upon checking the apps status, there arw a lot of apps marked in red: which I assumed were not backed up (apps and/or respective data).
> Also, selecting apps to exclude from backup is not persistent: after a backup all apps are selected again...

These sound like issues you should report upstream:

https://github.com/stevesoltys/seedvault

However, it's important to note that apps can fully disable backups, exclude lists of files from backups or provide their own implementation of the backup process. For example, Signal's database is encrypted with the keystore and a backup of the file would be useless. You need to use Signal's own backup mechanism. It rightfully disables the standard backup support. Some other apps disable backups for bad reasons or because they're unwilling to do the work of blacklisting files that should not be backed up such as data specific to the installation / device or things like login tokens that can simply be created by logging in.

**Comment by thestinger** [comment]
> Many apps have poor support for it even though most apps can fully support it by simply not doing anything like disabling support for backups.

In general, you'll need to take that up with app developers. The reason that Vanadium largely doesn't support the standard backup mechanism is because Chromium doesn't use it. They use their own sync mechanism instead, and omit that data from the app backups by using their own backup provider. You'll just need to be aware that some apps disable support for it and others choose to blacklist a lot of data from being backed up.
