### ISSUE TITLE
Seamless Update Client

### ISSUE THREAD

**Issue by amsurana** [GrapheneOS/os_issue_tracker#196]
Seamless update client uses too much data in background. I changed it to permitted network of download to `Any`
I am using a custom OS build, so update might not have gone through or download has been consistently failing for some reason.

Suggestions:
1. Never download update if it's not the build fingerprint is not same as that of release.
2. Show notification if download fails consistently.

![device-2020-03-29-112007](https://user-images.githubusercontent.com/817920/77842475-2f4d4f80-71b0-11ea-8577-7574a63153d0.png)

**Comment by thestinger** [comment]
You need to either omit the Updater app or point it at your own update server. You shouldn't include Updater pointed at the releases.grapheneos.org server with a custom build. Those update packages aren't compatible with your build of the OS and will also fail to pass signature verification, resulting in the downloads being deleted as corrupt once they're finished. In normal operation, downloads are never corrupted in practice due to TLS. Once the download is finished, which may take multiple attempts, it will pass signature verification and won't be deleted.

You're also downloading full update packages instead of deltas, which isn't the common case. That's happening because you're either multiple versions behind, you didn't use a stable release tag or you didn't set `BUILD_NUMBER` to match the stable tag.

I'll figure out something like omitting the Updater app from builds without an environment variable set so that people don't include it in their custom builds by default.

**Comment by thestinger** [comment]
https://github.com/GrapheneOS/platform_build/commit/039ff377de9f0283ae2d0d527f3752724ca86000 is an initial attempt at avoiding this problem.
