### ISSUE TITLE
PDF file fails to open from notification drawer

### ISSUE THREAD

**Issue by h2dden** [GrapheneOS/os_issue_tracker#201]
I am downloading a pdf file, wait for download to complete then from the notification drawer I tap to open the file. Pdf Viewer opens but it is blank, nothing is displayed.
When navigating to the Downloads folder and taping the file to open, Pdf Viewer displays the file correctly.
Sample file:
https://www.google.com/url?q=https://d13qmi8c46i38w.cloudfront.net/media/UCPthyssenkruppBAIS/assets.files/products___services/fertilizer_plants/ammonium_sulphate_plants/brochure-ammonia_scr.pdf&sa=U&ved=2ahUKEwjJht_Wz93oAhWUuJ4KHYjNBGQQFjAEegQICRAB&usg=AOvVaw3u1uAvJwA3QwBDzSBVUy8e

**Comment by beerisgood** [comment]
Which browser did you use?

**Comment by h2dden** [comment]
Firefox, but I dare to say it does not matter: I tap to open the file from notification drawer, once the download is complete, not from within the app.

**Comment by beerisgood** [comment]
> Firefox, but I dare to say it does not matter: I tap to open the file from notification drawer, once the download is complete, not from within the app.

Firefox doesn't support this in the right way. Vanadium does

**Comment by thestinger** [comment]
> Firefox, but I dare to say it does not matter: I tap to open the file from notification drawer, once the download is complete, not from within the app.

A notification in the notification drawer created by Firefox will run Firefox code when you interact with it. This is a bug in Firefox and is part of serious set of privacy and security limitations with it caused by their continued reliance on the legacy storage model and their flawed legacy approach to sharing files. They are aware of the bug and chose not to fix it because they disagree with having a proper security model for storage and don't have respect for the user's privacy or security:

https://hg.mozilla.org/mozilla-central/rev/9175cafb84bd

It's impossible to work around this in the PDF Viewer app. PDF Viewer cannot open a file: URI passed by Firefox for data in the user's home directory because it doesn't have the Storage permissions. The Storage permissions do not exist anymore for modern apps. Originally, not using the Storage permission was a design decision in PDF Viewer to provide better privacy and security at the expense of compatibility with broken apps like Firefox and Amaze. However, it's no longer a design decision by PDF Viewer. The Storage permissions are obsolete and were removed for the current API level. The only way to use those obsolete permissions is marking the app as using the legacy storage model to temporarily opt into using it. PDF Viewer is not a legacy app requiring the legacy storage model and that wouldn't be appropriate. Opting into the legacy storage model is no longer possible with the next API level coming with Android 11, which PDF Viewer will soon be targeting.

Passing file: URIs between apps was officially deprecated in Android 7 and Mozilla chose to disable the checks and break compatibility with privacy / security respecting apps not depending on the Storage permissions. Apps like Firefox causing these compatibility issues for other apps are a huge part of the reason that the unnecessary Storage permissions were so pervasive in the broader app ecosystem. You're demonstrating how apps like Firefox end up coercing other app developers into adding these unnecessary permissions to work around them because users blame the wrong apps for the compatibility issues.
