### ISSUE TITLE
Vanadium still has storage permission

### ISSUE THREAD

**Issue by kopolee11** [GrapheneOS/os_issue_tracker#203]
I am on GrapheneOS 2020.04.07.10 and this is regarding Vanadium 80.0.3987.162

Reading Daniel's comments on the GrapheneOS subreddit, I learned that modern Android apps no longer have the storage permission. I noticed that Vanadium still has the storage permission. Is this something that will be addressed? Thanks!

**Comment by thestinger** [comment]
Vanadium doesn't need the storage permission anymore. You can disable the leftover toggle already. This is just how things work due to upgrading.

**Comment by thestinger** [comment]
Vanadium is a standalone project with an issue tracker at https://github.com/GrapheneOS/Vanadium/issues. There's already an issue filed about the leftover legacy Storage permission, which is not used by the new downloads implementation:

https://github.com/GrapheneOS/Vanadium/issues/64

It's not something that it actually uses but rather is leftover cruft. Someone needs to test if it's even present after a factory reset / fresh install rather than the legacy storage model just remaining enabled for apps that were already installed before. If it's not present for fresh installs, the issue on the Vanadium tracker can be closed already without needing to do anything more.

**Comment by kopolee11** [comment]
Apologies for not checking the Vanadium issue tracker. Thank you for already addressing this issue.

**Comment by thestinger** [comment]
We mostly just need someone to check if the toggle is still present after a factory reset. If it's not, then there's no issue, it's only present because Vanadium originally required it and no longer does so it was carried over from the initial installation. That's how we expect things to work.
