### ISSUE TITLE
Option to route all traffic through the Tor Network w/ stream isolation

### ISSUE THREAD

**Issue by cyanlemons** [GrapheneOS/os_issue_tracker#210]
Although alternatives such as Orbot exist, I believe there is a case to be made for an OS-level implementation to route all traffic through the Tor Network. Tails, Whonix and QubesOS are examples that immediately come to mind of operating systems that allow one to route all traffic through the Tor Network.

As a privacy (and security) focused OS, I do believe it's within the bounds of helpful features that would benefit many of the users. In fact, when Edward Snowden described how he would use GrapheneOS, [routing all traffic through Tor](https://twitter.com/Snowden/status/1175430722733129729) was one of the first steps he'd take.

I do not believe Orbot is a suitable solution for the following reasons:
- Orbot does not perform any stream isolation – i.e. all applications on your phone will see the same IP from the same exit node
- Being at the application layer, any IP leak guarantees will inherently be weaker than an OS level implementation
- Orbot hasn't been updated in months and has many unresolved bugs

As most android applications will have some kind of network connection, any isolation obtained via the use of profiles is diminished by the fact that the public-facing IP will be the same for all of them. Of course, one could setup a per-app VPN for each application, but a VPN isn't as good as Tor, and it would be a very onerous task.

For these reasons, I would be very pleased to see an option in GrapheneOS allowing one to route all traffic through the Tor Network with stream isolation. The original Tor proposal to separate streams across circuits may be viewed [here](https://github.com/torproject/torspec/blob/master/proposals/171-separate-streams.txt).

**Comment by thestinger** [comment]
> Although alternatives such as Orbot exist, I believe there is a case to be made for an OS-level implementation to route all traffic through the Tor Network.

Android provides generic app-based proxy support with protection against leaks. The proper way to implement Tor support is with an unprivileged app. It would be inappropriate to make any invasive changes or write any privileged code for Tor support. It belongs in an app, as does support for any other kind of proxy requiring a service. Privilege separation, sandboxing and the permission model are not a negative thing and do not get in the way of implementing this properly. I don't think there's any reason not to take the standard app-based approach and you haven't come up with a reason.

See https://grapheneos.org/faq#vpn-support which provides an overview of the support provided by the OS. Unless there's an actual limitation with what can be done with this, there should be no reason to file an issue about it.

> Tails, Whonix and QubesOS are examples that immediately come to mind of operating systems that allow one to route all traffic through the Tor Network.

Android allows you to route all traffic via the Tor network with protection against leaks via the standard VPN service functionality provided to apps. Android isn't a traditional Linux distribution without a proper application security model and functionality designed around it.

> Orbot does not perform any stream isolation – i.e. all applications on your phone will see the same IP from the same exit node

That's an issue with Orbot and is not related to whether or not the functionality is built into the OS.

> Being at the application layer, any IP leak guarantees will inherently be weaker than an OS level implementation

The implementation is provided by the OS, not the app. The OS routes traffic through the VPN service app and prevents leaks. The app is not responsible for making sure all traffic is routed through it but rather only for handling that traffic properly. There is no limitation that would be addressed by hard-wiring Tor support into the OS. The generic support that's already provided by the OS works properly.

> Orbot hasn't been updated in months and has many unresolved bugs

That's not relevant to whether this functionality should be built into the OS. Orbot does not meet our standards and we have no interest in bundling it into the OS. It would need to 

> As most android applications will have some kind of network connection, any isolation obtained via the use of profiles is diminished by the fact that the public-facing IP will be the same for all of them.

I don't understand the point you're trying to make here. Profiles are the proper way to have separate identities and per-profile VPN services are fully supported. If you use profiles and set up Orbot or another VPN service in each profile, you already get what you want.

> Of course, one could setup a per-app VPN for each application, but a VPN isn't as good as Tor, and it would be a very onerous task.

The appropriate way to implement Tor support on Android is with a VPN service. It makes sense to want a better implementation of that than Orbot, but there is no reason to want this functionality built into the core OS rather than the appropriate place to do it which is the standard app sandbox.

**Comment by thestinger** [comment]
> Although alternatives such as Orbot exist, I believe there is a case to be made for an OS-level implementation to route all traffic through the Tor Network.

Android provides generic app-based proxy support with protection against leaks. The proper way to implement Tor support is with an unprivileged app. It would be inappropriate to make any invasive changes or write any privileged code for Tor support. It belongs in an app, as does support for any other kind of proxy requiring a service. Privilege separation, sandboxing and the permission model are positive things and do not get in the way of implementing this properly. I don't think there's any reason not to take the standard app-based approach and you haven't provided one.

It sounds like you're unhappy that Orbot is poorly implemented and maintained, and you want to try to get us to fork it and take over maintenance, which is not going to happen. There is no actual reason that this needs to be implemented in the OS. GrapheneOS should not be seen as a way to get development resources for creating apps you want written.

See https://grapheneos.org/faq#vpn-support which provides an overview of the support provided by the OS. Unless there's an actual limitation with what can be done with this, there should be no reason to file an issue about it. See https://grapheneos.org/faq#bundled-apps for an explanation of why we aren't interested in bundling assorted apps into the OS.

> Tails, Whonix and QubesOS are examples that immediately come to mind of operating systems that allow one to route all traffic through the Tor Network.

Android allows you to route all traffic via the Tor network with protection against leaks via the standard VPN service functionality provided to apps. Android isn't a traditional Linux distribution without a proper application security model and functionality designed around it. It would go against the core design and values of GrapheneOS to unnecessarily write invasive / privileged code for the core OS when it can be done properly in an unprivileged app.

> Orbot does not perform any stream isolation – i.e. all applications on your phone will see the same IP from the same exit node

That's an issue with Orbot and is not related to whether or not the functionality is built into the OS. This is a reason to fork Orbot or write a better implementation of Tor support from scratch, not a reason to move the functionality into the core OS.

> Being at the application layer, any IP leak guarantees will inherently be weaker than an OS level implementation

The implementation is provided by the OS, not the app. The OS routes traffic through the VPN service app and prevents leaks. The app is not responsible for making sure all traffic is routed through it but rather only for handling that traffic properly. There is no limitation that would be addressed by hard-wiring Tor support into the OS. The generic support that's already provided by the OS works properly.

> Orbot hasn't been updated in months and has many unresolved bugs

That's not relevant to whether this functionality should be built into the OS. Orbot does not meet our standards and we have no interest in forking it or bundling it into the OS. If you want to start writing a new implementation from scratch, that would make sense. GrapheneOS does not have the resources or interest to participate. The most I can do is say how I think it should be done, similar to how I laid out the concepts for the backup service implementation and others ended up implementing Seedvault. Unlike a backup service, a VPN service app does not need to be bundled with the OS to whitelist it. Since we don't need to bundle it, why should we? We aren't going to bundle apps like Signal either since it's simply not necessary.

> As most android applications will have some kind of network connection, any isolation obtained via the use of profiles is diminished by the fact that the public-facing IP will be the same for all of them.

I don't understand the point you're trying to make here. Profiles are the proper way to have separate identities and per-profile VPN services are fully supported. If you use profiles and set up Orbot or another VPN service in each profile, you already get what you want.

> Of course, one could setup a per-app VPN for each application, but a VPN isn't as good as Tor, and it would be a very onerous task.

The appropriate way to implement Tor support on Android is with a VPN service. It makes sense to want a better implementation of that than Orbot, but there is no reason to want this functionality built into the core OS rather than the appropriate place to do it which is the standard app sandbox.

**Comment by cyanlemons** [comment]
I see. I understand your reasoning. I was under the impression the reason Orbot did not implement stream isolation was due to a limitation of Android VPNs, but if a VPN application has access to such connection metadata and the implementation is the only part missing, then I would would be interested in writing an alternative.

If you have any insight or suggestions, particularly if you think it would be preferable to start from scratch or fork Orbot, I would be delighted to hear it.

**Comment by thestinger** [comment]
VPN apps have access to which app the connection is tied to.

**Comment by thestinger** [comment]
I think it would be best to start over from scratch. It's very easy to create a VPN service implementation and there are many things that Orbot does incorrectly.

There's a sample app at https://android.googlesource.com/platform/development/+/master/samples/ToyVpn/ although I haven't looked at it and I don't know how modern it is. It's probably fairly old but you could use it as a reference nonetheless.

You should bundle the Tor executable in the native library directory so that it can be executed on the latest API level, where running executables from app data is no longer permitted as part of working towards a full w^x implementation for memory and storage. GrapheneOS enforces a full implementation for base system apps, but many apps break best practices and aren't compatible with it so it can't be globally enforced and third party apps are currently omitted from it. Android 10 took another step forward and started enforcing it for executables.

**Comment by thestinger** [comment]
You can see that the VPN service can handle packets one by one. It can parse information from the packets and look up the connections in /proc/net/tcp6 and /proc/net/tcp. Tor doesn't support UDP or ICMP so I assume you would just be dropping those. You should be able to maintain consistency by essentially implementing a basic stateful firewall.
