### ISSUE TITLE
Please add some guidance about anti-virus

### ISSUE THREAD

**Issue by BillDietrich** [GrapheneOS/os_issue_tracker#2106]
Is installing an anti-virus app strongly discouraged, harmful, okay, encouraged ?  Are any of them known to cause problems, or not work ?

Please add a little text about this to the Usage or FAQ pages of the web site.  Thanks.

**Comment by thestinger** [comment]
We can't cover everything in the FAQ.

AV apps have extremely little purpose / benefit. Android apps are sandboxed, including an antivirus app. They can look at the list of apps installed in the same profile and their packages (APKs). They can't do anything beyond detecting malware based on what they've seen before which is barely useful. It has no value against any moderately sophisticated attack. The only value is detecting widespread, low sophistication malware where the user needs to explicitly download it, install it and grant it file access, contacts access, accessibility service access, device manager access, etc. Don't ever grant the dangerous permissions like accessibility service or device manager access, don't grant file permissions rather than using our Storage Scopes feature and be careful about granting permissions.
