### ISSUE TITLE
Cellular data does not work

### ISSUE THREAD

**Issue by Sakej99** [GrapheneOS/os_issue_tracker#216]
After installing Graphene I could not receive any group messages or browse the web with cellular. I tried removing Graphene and cellular worked, I reinstalled Graphene and still had the same issue. I tried downloading for the Pixel 3 the Beta and Stable versions.

**Comment by thestinger** [comment]
Cellular data works fine. This isn't an actionable issue. It sounds like an issue with your carrier.

**Comment by beerisgood** [comment]
@Sakej99 
Sounds like you need to config your APN settings.
AOSP doesn't include all like stock ROM

**Comment by thestinger** [comment]
If you need support you should ask for help on the #grapheneos IRC / Matrix channel. Cellular data works on GrapheneOS. At a bare minimum, you'll need to specify the carrier and device along with relevant details like APN configuration. There's no way that anyone could help you with this request for help and it's not a valid issue report. The issue tracker isn't used to provide support.

GrapheneOS doesn't support all of the carrier functionality supported by the stock OS and the default APN configuration won't always work. In some cases, you'll need to change in the APN configuration. In other cases, you'll need to use a different carriers.

Carrier support can be expanded including more closely matching the configuration and functionality provided by the stock OS, but that requires contributions to the project and device maintainers working on these areas. It isn't a bug and feature requests aren't helpful since it's known to be something that requires ongoing maintenance which is not being done due to lack of contributors and device maintainers. At the moment, none of the supported devices have maintainers working on this.
