### ISSUE TITLE
Dark theme does not auto-enable

### ISSUE THREAD

**Issue by jpds** [GrapheneOS/os_issue_tracker#225]
Minor nit but if I enable the dark theme in the settings to start at sunset, it never actually activates:

![signal-2020-06-09-222654](https://user-images.githubusercontent.com/29158971/84203180-e7e11a80-aaa0-11ea-8f94-fd2f584a378a.jpg)

I'm not sure if I'm simply missing a permission somewhere.

**Comment by thestinger** [comment]
This is because we don't have a coarse location service and it doesn't use fine location.

**Comment by thestinger** [comment]
See https://github.com/GrapheneOS/os_issue_tracker/issues/24. Since the cause is known (same for night light), I prefer to only have that issue about it.

**Comment by ldepandis** [comment]
@thestinger, sorry for commenting on a such and old issue. I don't want to necropost, so feel free to delete it if you want.

How about implementing a manual schedule feature, instead of a location-based one?
I attach the Night light config from GNOME Settings
![Screenshot from 2022-10-18 19-08-56](https://user-images.githubusercontent.com/77971920/196499054-f613c111-9e32-418e-8265-781849cb5ecf.png)


I think this could be an acceptable compromise between comfort and privacy.

What do you think about it?
