### ISSUE TITLE
IMA/EVM integration

### ISSUE THREAD

**Issue by jpds** [GrapheneOS/os_issue_tracker#231]
There seem to be some old patches for IMA/EVM on Android here:

- https://sourceforge.net/p/linux-ima/wiki/Home/#using-imaevm-on-android

Could these be possibly integrated into GrapheneOS to provide additional protection of system-level files?

**Comment by thestinger** [comment]
There's already full verified boot for the OS images including rollback protection. The hardwar-based attestation integrates with that and provides hardware-based attestations including the verified boot key, verified boot state and OS image patch levels. We don't use APEX components, but if we did, those use verified boot to verify out-of-band component updates. The fs-verity feature is used to verify out-of-band privileged apk updates. What would be the purpose of this?

**Comment by jpds** [comment]
Could the EVM system be leveraged to cryptographically sign every system file, thus preventing them from being changed by a sophisticated malicious process while the system is running?

**Comment by thestinger** [comment]
The OS images are signed and verified in their entirety, not just the contents of files but all of the filesystem layout. The images are either not mounted (boot, dtbo) or mounted as read-only. An attacker that has compromised the OS to the extent that could modify any of this is in the position to bypass any kernel security features.

**Comment by thestinger** [comment]
The OS verified boot and attestation covers all the OS images: vbmeta, dtbo, system, vendor, product. Firmware that's stored outside the OS is also verified too. For the OS, only the data partition isn't verified, since it's where persistent state is stored. It's what's wiped by a factory reset along with the security chip state, etc. Apps and components there can still be verified via fs-verity or by shipping them as filesystem images (APEX components) covered by verified boot.

**Comment by jpds** [comment]
Thanks for taking the time to explain this @thestinger - I now see why this is redundant.
