### ISSUE TITLE
Network-provided time disabled, still resolves time.grapheneos.org

### ISSUE THREAD

**Issue by rustybird** [GrapheneOS/os_issue_tracker#232]
I've disabled network-provided time, but my router's DNS log still shows recurring attempts to resolve the IP address of `time.grapheneos.org`. This prevents GrapheneOS (2020.06.02.02) from blending in with other Android devices.

**Comment by thestinger** [comment]
cc @renlord

**Comment by thestinger** [comment]
Strange, since I think we rely on the upstream code to decide when to do this.

**Comment by rustybird** [comment]
That make sense: When I would set up an old non-GrapheneOS phone, I used to run `settings put global ntp_server 127.0.0.1`. IIRC the purpose was to get rid of the same stray DNS resolve with regular NTP.

**Comment by thestinger** [comment]
I think the issue might be that the upstream toggle currently only controls whether the network-based time is used but doesn't actually control whether network-based time is kept up-to-date.

**Comment by thestinger** [comment]
We'll need to add an extra branch somewhere to bail out when it's disabled. It should be a really easy 3-5 line fix.

**Comment by renlord** [comment]
have you also tried changing `config_ntpMode`?
If you want to mimic stock android, you need to set that to `ntp`.
If you do that, then the time detector service will swtich back to using whatever server you've set for `config_ntpServer`, otherwise the default ntpMode is currently set to `https` which consumes the `config_httpsTimeServer` field in the config instead.

**Comment by thestinger** [comment]
@renlord The issue is that the toggle for network time in the stock OS only disables using the time, not fetching it, so we need to add a check for whether network time is enabled somewhere to disable fetching the time when it's disabled. It's an upstream issue impacting us since we deviate from how the time is fetched.

**Comment by thestinger** [comment]
This is very important since we want people to be able to avoid connections identifying the device as GraphenOS without needing to use a VPN.

**Comment by renlord** [comment]
@thestinger https://github.com/GrapheneOS/platform_frameworks_base/pull/29

**Comment by renlord** [comment]
dont really think its a bug since upstream still pings servers when you disable nitz, should be called a feature instead.

**Comment by thestinger** [comment]
@renlord I think it's currently using the wrong setting. It's using the resource rather than the dynamic runtime configuration via Settings.

**Comment by renlord** [comment]
Ah OK. I will change to use this: `Settings.Global.AUTO_TIME`
