### ISSUE TITLE
Seedvault needs to be ported to Android 11

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/os_issue_tracker#266]

**Comment by chirayudesai** [comment]
https://github.com/stevesoltys/seedvault/issues/94

**Comment by grote** [comment]
Porting done in https://github.com/grote/seedvault/commits/android11-staging and considered ready, just needs more testing.

**Comment by thestinger** [comment]
Okay, switched to that code for now along with building it in-tree. I'll let you know if we run into any issues. Still don't have SetupWizard though.

**Comment by thestinger** [comment]
@grote First problem:

```
build/make/core/main.mk:1206: warning:  build/make/target/product/sdk_phone_x86_64.mk produces files inside build/make/target/product/mainline_system.mks artifact path requirement. 
Offending entries:
system/etc/permissions/permissions_com.stevesoltys.seedvault.xml
system/etc/sysconfig/whitelist_com.stevesoltys.seedvault.xml
system/priv-app/Seedvault/Seedvault.apk
system/priv-app/Seedvault/oat/x86_64/Seedvault.odex
system/priv-app/Seedvault/oat/x86_64/Seedvault.vdex
```

**Comment by thestinger** [comment]
Okay, that seems to have been resolved by moving it from handheld_product to media_system.

**Comment by grote** [comment]
Great that things are working out so far. If SetupWizard is only needed to trigger restore, maybe there is another way to launch an intent with the action `com.stevesoltys.seedvault.RESTORE_BACKUP` as a workaround. Or temporarily enable the in-app restore option in `config.xml`.

Otherwise, please note that I might still be force pushing to that android 11 branch and appreciate testing feedback, since you seem to be further ahead in the Android 11 release process.
