### ISSUE TITLE
Swiping down after switching user profiles at lock screen does not work anymore in latest beta.

### ISSUE THREAD

**Issue by Lia-EoT** [GrapheneOS/os_issue_tracker#328]
Just a minor UI/UX inconvenience, but the done button can be pressed anyways.

**Comment by inthewaves** [comment]
Seems to be an upstream change and not something GrapheneOS did; I can observe this behavior on AOSP (android-11.0.0_r1).

My guess is that they did this so that they can manage the case where there are many users/profiles to the point where you might have to scroll the grid of users to select the user/profile you want to switch.

Before, on Android 10, swiping up was used to both collapse the panel and scroll the grid down. So, when I was testing a feature involving multiple profiles (GrapheneOS supports a max of around 16), I often ended up in situations where I couldn't even scroll the grid of users, because doing so ended up being a gesture to collapse the panel. I had to do some odd maneuver where I had to swipe down and hold over the grid first to set the focus to the grid of users, and then I was able to scroll down by swiping up.

**Comment by thestinger** [comment]
This is an upstream issue.

**Comment by thestinger** [comment]
I don't really know if it's a bug or intended.

**Comment by thestinger** [comment]
Going to close this for now. It should probably just be addressed upstream if at all.
