### ISSUE TITLE
Screenshot and apps not working

### ISSUE THREAD

**Issue by adtvp** [GrapheneOS/os_issue_tracker#341]
Power button used to created screenshots based on long presses and apps like Plex not working since the update. Any way of rolling back to previous version I can't find the install.

**Comment by thestinger** [comment]
You can take screenshots as you could before using power + volume down. There's not a screenshot button in the power menu anymore in Android 11. It's possible we could add it back there, but it's meant to be moved to the recent apps menu. It seems we don't have this enabled. It's working fine though.

> apps like Plex not working since the update

You need to create separate issues for different issues. Make sure that you're not simply running into the issue of F-Droid having broken app builds in their main repository. They still have apps with v1 signatures, and if those apps claim to target API 30+ that is disallowed, so the apps are disabled if they were installed.

https://developer.android.com/about/versions/11/behavior-changes-11#minimum-signature-scheme

This is intended. v2 signatures were released in 2016 as part of Android 7 as a security update. The stable SDK tools switched over to it before the stable release of Android 7. It's fully backwards compatible and the intention was for all apps to be signed with v2+ signatures from that point.

For whatever reason, F-Droid continued using the less secure v1 signatures. This wouldn't have happened if they signed with the official apk signing tool. They ended up continuing this even with apps using targetSdkVersion 30+ which creates broken apks. Android 11 is where support for targetSdkVersion 30+ is implemented. It is no different than 29 on Android 10 since it only supports 29+. That's why nothing actually went wrong until upgrading.

Not much we can do about F-Droid having broken apk builds in their repositories. They should have promptly rebuilt all of these apps rather than waiting until the next release. It's not clear why they still aren't reacting to this promptly.

**Comment by thestinger** [comment]
F-Droid has fixed the issue for their builds, but they have not rebuilt all of the apps impacted by it. Make sure that this is not the issue you're seeing before filing issues about apps that aren't working. The broken app build is probably still installed on your device. It's just disabled because it's broken. Once they release a working build, you'll be able to update it and use the app with your data again. I think there's an issue on their tracker with a list of apps that are still broken in their repositories. Maybe you could request that they fix them ASAP instead of waiting.

**Comment by thestinger** [comment]
You can't roll back updates both for security reasons and because it simply wouldn't work in many cases regardless.

Android 10 doesn't support using persistent data from Android 11. It's not something specific to Android but rather you can't just take data from a new version of software and use it with an old version unless it goes out of the way to preserve that kind of compatibility like SQLite. Most software including most apps don't do that, and the OS is a collection of *many* software projects where *many* of them are not doing that. There are a bunch of changes to data that would not be backwards compatible. You can't simply downgrade a major release of software after your data has been migrated to the new version.

Downgrade attacks are a serious security issue so the update system, hardware-backed keystore and verified boot all have downgrade protection. The only way to 'downgrade' would be installing an update explicitly marked as a permitted downgrade and it would need to be marked as providing an equal or greater security patch level or it would be rejected by the keystore and verified boot downgrade protection. Our final Android 10 release had a lower security patch level than our current releases (2020-09-01 instead of 2020-09-05) so even if we wanted to sign and public a downgrade package, we do not have that option available. We also can't get the 2020-09-05 or greater patch level for these devices with Android 10 easily. There is no realistic way forward using Android 10 on these devices.

Consider getting apps from a more reliable source than F-Droid such as Aurora Store. This issue was caused by negligence and lack of maintenance. v1 signatures had a negative security impact on users for 4 years before finally breaking due to them having apps marked as API 30+ still using them. It is a good thing that it finally broke and they have to update, but consider what this shows about F-Droid. It still relies on SHA-1-based signatures, etc. among other issues.

**Comment by inthewaves** [comment]
> It's possible we could add it back there, but it's meant to be moved to the recent apps menu. It seems we don't have this enabled

It's currently shown when using the 3-button and gesture navigation options, but not with the 2-button option
