### ISSUE TITLE
[Enhancement] Add clipboard control for user apps

### ISSUE THREAD

**Issue by githupper** [GrapheneOS/os_issue_tracker#346]
Would like to request (if functionality possibility permits) to have clipboard monitor similar to using Riru and AppOps that detects and default permits/deny clipboard copying in apps.

Some apps and even those hosted in FDroid like Bromite tries to read clipboard data each time the app goes into focus (not cold launch). AppOps is able to have a default deny or allow rule for each app and when a denied app tries to read clipboard data, a transparent popup at the top to allow a one time allow if the user wishes. This is useful when a user actually wants to allow clipboard copying rather than allows any app to read when in focus.

The use case for this to be built in is that that when a user uses password managers, they usually automatically copy the password to the clipboard and some does not offer auto clipboard deletion. This is bad if a user uses the password managers to login into banking apps and when done, open Facebook or browser which then automatically reads the clipboard which contains the password.

Automatically reading of clipboard seems to be quite widespread in many apps, much like what iOS 14 found out when it start detecting and alerting users that apps copy their clipboard.

I am currently not sure if Riru and AppOps can work in GrapheneOS but if it's not usable, would like to request GrapheneOS devs to consider building it in.

I understand that you had addresed this in Reddit before but please consider how AppOps is addressing the user experience currently and if it addresses your original concerns earlier.

Thank you

**Comment by thestinger** [comment]
> The use case for this to be built in is that that when a user uses password managers

This is not an appropriate way to implement password managers. They are supposed to use the autofill service and can offer a keyboard implementation as a more generic fallback approach.

**Comment by thestinger** [comment]
Decent password managers do not function the way you describe.

**Comment by thestinger** [comment]
This is not how we intend to approach clipboard access.

The status quo is that only the focused app can read the clipboard.

Your issue report gets a lot of the details wrong and the proposed approach would have bad usability and privacy properties compared to a more sensible approach like a paste button in the keyboard paired with a toggle to disable API-based clipboard access.

**Comment by githupper** [comment]
Not sure if you would class Bitwarden as an appropriate password. It does not always 100% auto fill in the password, whether it is for apps or general websites. In such cases, the logical way would be to use the copy password function and manually paste into the password field. Especially so when the original intention of having a password manager is to have a complex password of reasonably long length.

**Comment by thestinger** [comment]
Read my comments and #347.

**Comment by thestinger** [comment]
> Not sure if you would class Bitwarden as an appropriate password

It doesn't sound like it's a good password manager if you have to copy passwords via the clipboard rather than using an autofill service and/or password manager keyboard.

> copy password function and manually paste into the password field

The logical response is to use a proper password manager.

> this has been found out by AppOps since it shows an alert when an app does that.

You're confused about what AppOps is and you're using the term to refer to something else. I don't know what you're actually talking about, but it's not AppOps itself.

I'm also really not sure on the relevance to what I posted. I understand what you're talking about. Your proposed solution isn't a good one. It has bad usability and privacy properties compared to our planned approach. We don't want to add a per-app toggle for the ability to read the clipboard rather than giving the user the option to take control over pasting from the clipboard. Read my comments and the issue I filed about our plans for the clipboard.

**Comment by thestinger** [comment]
Permission toggles are not a good design for access control. They're a last resort when there isn't a clear way to make a better implementation with case-by-case consent / control. The OS has moved away from using coarse permission toggles at great effort, such as deprecating the Storage permission and phasing it out.

Users do not simply want to allow or disallow an app from reading the clipboard. Sometimes they want to paste the clipboard into an app and that doesn't mean they want to trust the app with persistent access to the clipboard. The proposed implementation of a toggle is not a good approach. It doesn't make sense to repeat historical mistakes which the OS has moved past for designing new features. I think the problems of a permission model design are very clear.

> If this does not suit GrapheneOS design philosophy, then perhaps consider a clear clipboard function.

That's not a good approach either. It depends on the user always remembering to clear data from the clipboard after switching directly to the app where they want to paste it. It's not a good design. Why do you insist on these hacky approaches instead of an option to disallow API-based clipboard read access along with a paste button on the keyboard? With a physical keyboard, we can intercept the usual C-v binding, although that would be a low priority to implement.

**Comment by thestinger** [comment]
Permission toggles are not a good design for access control. They're a last resort when there isn't a clear way to make a better implementation with case-by-case consent / control. The OS has moved away from using coarse permission toggles at great effort, such as deprecating the Storage permission and phasing it out.

Users do not simply want to allow or disallow an app from reading the clipboard. Sometimes they want to paste the clipboard into an app and that doesn't mean they want to trust the app with persistent access to the clipboard. The proposed implementation of a toggle is not a good approach. It doesn't make sense to repeat historical mistakes which the OS has moved past for designing new features. I think the problems with a permission toggle model design are very clear, and the proposed way of doing it would have usability issues beyond that. As I said, it's not a good approach, and we won't be doing it.

> If this does not suit GrapheneOS design philosophy, then perhaps consider a clear clipboard function.

That's not a good approach either. It depends on the user always remembering to clear data from the clipboard after switching directly to the app where they want to paste it. It's not a good design. Why do you insist on these hacky approaches instead of an option to disallow API-based clipboard read access along with a paste button on the keyboard? With a physical keyboard, we can intercept the usual C-v binding, although that would be a low priority to implement.

**Comment by thestinger** [comment]
Permission toggles are not a good design for access control. They're a last resort when there isn't a clear way to make a better implementation with case-by-case consent / control. The OS has moved away from using coarse permission toggles at great effort, such as deprecating the Storage permission and phasing it out.

Users do not simply want to allow or disallow an app from reading the clipboard. Sometimes they want to paste the clipboard into an app and that doesn't mean they want to trust the app with persistent access to the clipboard. The proposed implementation of a toggle is not a good approach. It doesn't make sense to repeat historical mistakes which the OS has moved past for designing new features. I think the problems with a permission toggle model design are very clear, and the proposed way of doing it would have usability issues beyond that. As I said, it's not a good approach, and we won't be doing it.

> If this does not suit GrapheneOS design philosophy, then perhaps consider a clear clipboard function.

That's not a good approach either. It depends on the user always remembering to clear data from the clipboard after switching directly to the app where they want to paste it. It's not a good design. With a physical keyboard, we can intercept the usual C-v binding, although that would be a low priority to implement.

**Comment by githupper** [comment]
> It doesn't sound like it's a good password manager if you have to copy passwords via the clipboard rather than using an autofill service and/or password manager keyboard.
> I have a couple of password managers, both paid and open source. Bitwarden just happened to be the one I am using the most. Other password managers I have also do not have a 100% successful auto fill rate. Obviously it they can perform at 100%, there is no need to do the manual way.

> The logical response is to use a proper password manager.
> As replied above. Any password manager that you are aware of that has 100% success on both apps and in browsers?

> > this has been found out by AppOps since it shows an alert when an app does that.
> 
> You're confused about what AppOps is and you're using the term to refer to something else. I don't know what you're actually talking about, but it's not AppOps itself.
 I think there is a miscomm. The app itself just happened to be called by the same name. https://play.google.com/store/apps/details?id=rikka.appops&hl=en

> I'm also really not sure on the relevance to what I posted. I understand what you're talking about. Your proposed solution isn't a good one. It has bad usability and privacy properties compared to our planned approach. We don't want to add a per-app toggle for the ability to read the clipboard rather than giving the user the option to take control over pasting from the clipboard. Read my comments and the issue I filed about our plans for the clipboard.

Do allow me to elaborate some of the points I mentioned earlier.
i) Some apps have the nasty habit of reading clipboard when in focus or on first launch
ii) Can we agree that such behaviour is not reasonable or necessary to always read the clipboard every single time? I believe Apple try to address this in iOS14 and suddenly apps like Instagram, LinkedIn suddenly roll out new versions immediately to stop doing that.
iii) A lot of things are copied into clipboard, not just passwords. And clipboard does not have a expiry timer on it. So all sorts of stuff are copied into it, without a way to clear the clipboard.
iv) Password copying is just one scenario that I am worried about, being that my password manager does not autofill all the time and I have to manually copy paste them sometimes. Other personal stuff or conversations are copied in them too.

Also I am not insisting on hacky approaches. If the devs have a better idea, then all the better. I am just proposing what I had in mind and what is available that works for my scenario for devs' considerations.

Just a last note, as you have not used the AppOps I was using before, just for sharing purposes (not a suggestion for this ticket), this are what it can do.

i) Global clipboard allow or deny for all apps
ii) For denied apps, there is a 15 seconds timer to allow a one time clipboard access. One scenario is such that you do not trust Facebook app but it so happens you just need to do a one time paste. the 15 seconds timer cater for that
ii) It allows per app customization.

 
#347 should address the issue I mentioned. Thank you for reacting to this ticket.

**Comment by thestinger** [comment]
Showing a message does not address the issue. It just makes users aware of it happening when they notice it.

**Comment by thestinger** [comment]
> Just a last note, as you have not used the AppOps I was using before, just for sharing purposes (not a suggestion for this ticket), this are what it can do.

AppOps is a low-level OS implementation detail used for various parts of the permission model and other things. You're talking about something else that isn't AppOps. I'm well aware of what AppOps provides, and you're wrong about it.

**Comment by githupper** [comment]
> 
> 
> > Just a last note, as you have not used the AppOps I was using before, just for sharing purposes (not a suggestion for this ticket), this are what it can do.
> 
> AppOps is a low-level OS implementation detail used for various parts of the permission model and other things. You're talking about something else that isn't AppOps. I'm well aware of what AppOps provides, and you're wrong about it.
![Capture](https://user-images.githubusercontent.com/25658765/94720596-43545280-0387-11eb-9dc7-8c591557b499.JPG)

Again I am not arguing about if you know what is and what is not AppOps but that the app from Rikku happened to be using that same name, that is all and that I am not wrong on addressing it as such.

**Comment by githupper** [comment]
> 
> 
> Showing a message does not address the issue. It just makes users aware of it happening when they notice it.

Showing a message does not address the underlying issue yes, but if we look at the drama created when iOS 14 flagged out so many apps that were doing that without users knowing, the impact is that once such knowledge is publicly available, they are inclined to "fix the bug" on their end.

These are some of the apps flagged out after being exposed.

![image](https://user-images.githubusercontent.com/25658765/94721352-57e51a80-0388-11eb-9a32-17108bee6fe1.png)

Wouldn't you call it the first step in addressing the issue?

**Comment by thestinger** [comment]
> Again I am not arguing about if you know what is and what is not AppOps but that the app from Rikku happened to be using that same name, that is all and that I am not wrong on addressing it as such.

You're wrong in addressing it that way. AppOps is a low-level OS implementation detail, and that app is not called AppOps.

**Comment by thestinger** [comment]
Correct usage of terms is important if you expect what you're saying to make sense and be understood.

**Comment by thestinger** [comment]
> Showing a message does not address the underlying issue yes, but if we look at the drama created when iOS 14 flagged out so many apps that were doing that without users knowing, the impact is that once such knowledge is publicly available, they are inclined to "fix the bug" on their end.

Which doesn't fix the issue of apps still being completely capable of doing it, and doesn't provide a way to stop it.

> Wouldn't you call it the first step in addressing the issue?

The only full solution is not having API-based access to the clipboard but rather having users explicitly paste via an OS API. Showing a notice when apps access the clipboard doesn't reduce their access at all. The wrong approach was taken to implementing the standard clipboard support in the first place. It should have been designed to use a system UI. iOS 14 didn't make any steps towards that.

**Comment by thestinger** [comment]
#347 is all that's relevant to this issue tracker.
