### ISSUE TITLE
Raise max password length from 64 characters to 128 characters

### ISSUE THREAD

**Issue by matchboxbananasynergy** [GrapheneOS/os_issue_tracker#3540]
GrapheneOS currently raises the max length for passwords to 64 characters. While that is ample for random passwords, people are more likely going to want to use diceware passphrases, as those are easier to remember. More specifically, they might want to use the EFF large wordlist which specifically chooses to use longer words on average to improve memorability of the list's words.

The longest word in that wordlist seems to be 9 characters. Assuming someone rolls the max, and assuming there's one space between each words, that's 99 characters for a 10 word passphrase using that list.

Going for 128 characters is clean (double of 64), and gives enough play for people to go even beyond 10 words without issues.

**Comment by neelchauhan** [comment]
I opened a PR for this in https://github.com/GrapheneOS/platform_frameworks_base/pull/521

**Comment by neelchauhan** [comment]
Sorry for the delay. I had to upgrade my laptop's RAM in order to build as I cannot run emulator on my GPU-less server and my desktop is packed.

I have some good news:

 * Yes, this patch does work
 * I also removed the newline from the PR

Demo: https://youtu.be/UugvPpYNwIM (The password being entered is on the right of the video in the terminal).
