### ISSUE TITLE
Visual voicemail broken after update to A11

### ISSUE THREAD

**Issue by solaslux** [GrapheneOS/os_issue_tracker#356]
Hi there,

After the recent update to android 11, visual voicemail stopped working. In the default phone app, no settings have changed wrt to voicemail and carrier confirms no changes on their end. Model is pixel 3 xl.
Notably, I have a pixel 3 (non-xl) with stock google ROM also on A11 with same carrier and no issued with visual voicemail.
This error continues despite try again not helping. Calling voicemail works as expected:
![Screenshot_20201005-235534_1](https://user-images.githubusercontent.com/72463919/95238190-c4b84480-07ce-11eb-8b29-5f0748511e00.png)

**Comment by thestinger** [comment]
This is *probably* an upstream issue we inherited but it could be caused by our updated APN database.

**Comment by thestinger** [comment]
It's not really surprising for Verizon to have issues since they expect to have a dozen proprietary Verizon apps and we don't include them, but this always worked in the past.

**Comment by solaslux** [comment]
My carrier is an mvno of T-Mobile. My APN settings are correct per the carrier. 

Thanks for chiming in. I don't seem to have any other connectivity issues: data, MMS, SMS, and calls work fine.

**Comment by z00kus** [comment]
Been meaning to actually post for quite some time.  Since upgrading to Android 11 on Visible, I've completely lost the option for visual voicemail.  I don't even get the prompt like the above user and when going through voicemail settings as well there is nothing even remotely close to it either.

It did work perfectly fine in Android 10 then.

**Comment by weston89** [comment]
Made an account just to comment on this. I'm loving GrapheneOS but the lack of voicemail notification is a huge negative. Visual voicemail being absent is a bit of a bummer, but its not having any voicemail notifications at all that is the bigger issue. I have missed several voicemail from work because there was zero indication I even had them.

@thestinger I think your doing amazing work on GrapheneOS. I just hope this can get sorted soon because its making it nearly unusable for me at the moment.

**Comment by thestinger** [comment]
Expressing that you want the issue fixed won't get it fixed any faster. It's a carrier issue and not something that I can work on without access to one of the carriers with the issue. It needs someone with the issue like you to work on it.

**Comment by thestinger** [comment]
I also have to seriously question why you are using GrapheneOS in the first place if you're willing to use an OS without full security updates for serious security issues. If you expected that kind of comment to encourage a developer to work on this, you couldn't be more wrong. If anything, you've done the opposite.

**Comment by renlord** [comment]
> Made an account just to comment on this. I'm loving GrapheneOS but the lack of voicemail notification is a huge negative. Visual voicemail being absent is a bit of a bummer, but its not having any voicemail notifications at all that is the bigger issue. I have missed several voicemail from work because there was zero indication I even had them.
> 
> @thestinger I think your doing amazing work on GrapheneOS. I just hope this can get sorted soon because its making it nearly unusable for me at the moment.

This is an issue with your carrier.
I can play voicemail via signal as my default (SMS) receiver, never had to phone voicemail.

**Comment by weston89** [comment]
> I also have to seriously question why you are using GrapheneOS in the first place if you're willing to use an OS without full security updates for serious security issues. If you expected that kind of comment to encourage a developer to work on this, you couldn't be more wrong. If anything, you've done the opposite.

I got GrapheneOS because I wanted to get rid of Google and it seemed like a good option. I wasn't attempting to demand anything or offend anyone. I apologize if it came off that way. I'm not incredibly tech wavy. I was just attempting to better my life by taking the baby step of ditching Google. I didn't mean to create hostility or upset anyone.

**Comment by thestinger** [comment]
Is this still an issue on the November release (2020.11.03.03)? If so, please give details including device model, carrier (be as specific as possible), APN configuration and what you've tried to do to resolve the issue.

**Comment by solaslux** [comment]
> Is this still an issue on the November release (2020.11.03.03)? If so, please give details including device model, carrier (be as specific as possible), APN configuration and what you've tried to do to resolve the issue.

Yes, I updated to 11.03.03 last night and the issue persists.
Model: Pixel 3 XL
Carrier: Mint Mobile (with APN setup as described here: https://www.mintmobile.com/setup-for-android/)

So far, I've tried wiping data/reset. MMS does not work reliably without the APN setup chosen above. Before the OS update to 11, Visual Voicemail (part of the stock dailer) worked with no issues. Now, it can display that a voicemail exists but cannot fetch it to play the audio, exactly like in the original image above. 

When the issue first happened, I called Mint and the customer support confirmed that the service was working on their end and my setup is correct per their instructions.

**Comment by Manbeard** [comment]
Just wanted to report that I am also experiencing this issue on both a Pixel 3XL and a Pixel 2 since updating to the A11 version of Graphene. Unfortunately it still persists even after updating the Pixel 3XL to 2020.11.05.18 and the Pixel 2 to 2020.11.07. Both phones are on Verizon.

Thanks!

**Comment by thestinger** [comment]
It's not likely this will be fixed for the Pixel 2 and 2 XL before they stop receiving updates.

**Comment by Manbeard** [comment]
No worries. I mainly use the Pixel 3XL...just wanted to report that it was affecting both.

BTW, thanks for this amazing OS! It checks every box I'm looking for in a Mobile OS and has been an absolute pleasure to use. 

Cheers!

**Comment by thestinger** [comment]
Please test on the 2020.12.08.08 release.

**Comment by solaslux** [comment]
I just updated to 2020.12.08.08 and it gives me the same error. I tried rebooting and I tried flipping to a default APN and back to see if that might help. 

Thanks for the hard work, I'll continue to test it with new releases.

**Comment by jim-perkins** [comment]
Is This the upstream area of concern ?  Thanks

https://github.com/AOSPAlliance/android-prepare-vendor/issues/28#issuecomment-696020676

**Comment by thestinger** [comment]
No, that part should be working fine. We manually add the APN configurations. AOSP alone wouldn't have these extended APN configurations. It's possible that the extended APN configurations from carriersettings-extractor are what causes the issue. It's also possible that it's caused by us enabling VVM3 in packages/services/Telephony. It may also be something missing in android-prepare-vendor, etc. I think it's pretty unlikely that it's caused by one of our changes aside from enabling VVM3.

**Comment by jim-perkins** [comment]
Thanks for the reply . We spoke earlier on irc.  I was the oldguy confused about extracitng the vender stuff and that aosp is not complete and secondly that other os's are still on android 10.  Doing more research now.  I am pretty sure i compiled aosp 11 without using android_prepare_vendor and vmm worked.  Did not use any verizon apps. will document fully this go roind

Does graphene have a US based developer that could benefit from a working verizon sim card to chase this down ?

thanks again.

**Comment by thestinger** [comment]
Try with our commit in packages/services/Telephony explicitly enabling VVM3. That may be what breaks it.

**Comment by thestinger** [comment]
Also, try with android-prepare-vendor instead of Google's driver packages.

Also need to try with our commit adding the expanded APN databases in the device repository. It may actually be the fact that we're applying the expanded APN databases without having the Verizon apps, etc. that is causing the problem. I don't know. It could also simply be broken with android-prepare-vendor + AOSP and without our changes relevant to this (updated/expanded APN databases + enabling VVM3 are the relevant changes we make).

**Comment by jim-perkins** [comment]
> I can play voicemail via signal as my default (SMS) receiver, never had to phone voicemail.

Just wanted to comment i instslled signal and it was not notified of voicemail.  Verizon pixel3xl

**Comment by kdrag0n** [comment]
I have no experience with Verizon but I can attest to Mint Mobile (a T-Mobile MVNO mentioned above that does not work otherwise) visual voicemail working on AOSP with a small fix: https://github.com/ProtonAOSP/android_vendor_proton/commit/10ca3e122d3fd9dce592ecef4b3e871c3d7c590a

Similar to APNs and carrier configs, VVM configs are necessary for it to work properly. The dialer app tries to connect to the voicemail IMAP server over plain-text IMAP otherwise and fails because T-Mobile's IMAP server does not support plain-text. The carrier's VVM config specifies the correct port for it to connect over IMAPS (among other settings), which makes it work as expected.

The correct VVM configs can be extracted from the Google Dialer APK. GrapheneOS will need to either fork the dialer app or add a build-time overlay to update the configs.

**Comment by jim-perkins** [comment]
@kdrag0n Thanks so much !!

Using a Pixel3XL I was able to get Verizon VMM working on a android 11 build of GrapheneOS  after replacing packages/apps/Dialer/java/com/android/voicemail/impl/res/xml/vvm_config.xml with the file listed in https://github.com/GrapheneOS/os_issue_tracker/issues/356#issuecomment-745051951

Basically I compiled BUILD_ID=RQ1A.201205.003 of GOS following the build instruction from the GOS website.  I compiled a development build ( w ).  flashed it to my device to verify it booted.  It booted but no VMM.  Then I replaced the file listed above and recompiled, did not do a 'rm -r out'.  The recompile only took a few minutes.  then I flashed that (fastboot flashall -w)and it had working VMM with verizon using a very recent GrapheneOS .

What needs to happen to get this into GrapheneOS.  ?  How can I help do that considering I am not a programmer. ?  thanks

**Comment by jim-perkins** [comment]
I have created a pull request which implemented https://github.com/GrapheneOS/os_issue_tracker/issues/356#issuecomment-745051951 on crosshatch hoping to get some discussion about the path forward on this.  https://github.com/GrapheneOS/device_google_crosshatch/pull/7

thanks

**Comment by linuxhelper** [comment]
This issue is also present on the Pixel 4A (RQ1A.201205.008.2020.12.08.08) w/ Mint Mobile (T-Mobile MVNO)—carrier specified APN settings used.

Voicemail inbox shows voicemails (caller, time, etc.), but hangs when attempting to play them, "Loading Voicemail".

Tech rep sent a replacement SIM citing a change in the system ~1yr or so ago and my unwillingness to use a 3rd party app. New SIM didn't resolve the issue. He gave it a 50% chance w/ Android. I hadn't found this bug report then though :)

![IMG_20201220_014442](https://user-images.githubusercontent.com/50037005/102710136-208a5980-4265-11eb-9f66-c575a5d560f4.jpg)

**Comment by danielk43** [comment]
Can confirm that @kdrag0n's [file](https://github.com/ProtonAOSP/android_vendor_proton/commit/10ca3e122d3fd9dce592ecef4b3e871c3d7c590a) contents replacing `packages/apps/Dialer/java/com/android/voicemail/impl/res/xml/vvm_config.xml` also restore VVM for Visible (see rows 216-238) on Coral/4XL; dev branch build, adb sideload of ota update zip. Thanks also @jim-perkins

**Comment by thestinger** [comment]
We now have a fork of the Dialer app at https://github.com/GrapheneOS/platform_packages_apps_Dialer. A pull request with the latest configuration from the Google Dialer app is welcome.
