### ISSUE TITLE
Wifi hotspot whitelisting

### ISSUE THREAD

**Issue by Lppsoeht** [GrapheneOS/os_issue_tracker#3785]
Feature request:
Ability to deny any new wifi connection from any device not listed in the whitelist.
For the feature to be useful, new WiFi connections tries should be limited to max 1 per x seconds.

**Comment by WaleedMortaja** [comment]
@thestinger Most of the people are not tech savvy to do such monitoring.
Sometimes, one wants to temporary kick a device to reduce the burden on the network without the hustle of changing the password (and then changing it on the clients).
I know that allow list is not perfect because of monitoring and spoofing. However, it is a very very good defense against most of the people.

**Comment by WaleedMortaja** [comment]
@thestinger One of the uses of hotspot is to share internet (coming usually from e/SIM). in that situation hotspot is used regularly. Anyway, do you mean WPA-Enterprise (radius) by "client keys"? Because I only see WPA-Personal options.
Thank you for your time and fast reply!
