### ISSUE TITLE
New Firewall features: Logging, IP ranges

### ISSUE THREAD

**Issue by ericschdt** [GrapheneOS/os_issue_tracker#389]
The [current firewall implementation](https://grapheneos.org/faq#firewall) to controll apps' traffic has pretty basic functionality: `Block / Allow`. 
It would be convenient to have additional functionality:

- Logging of incoming/outgoing traffic and its status
- Blocking/Allowing an IP range
  - This would allow to restrict apps eg to only the lan (useful for eg smart home apps)
- Filter lists of predefined IPs/DNS entries to be blocked for all apps

As an alternative I currently use the well written NetGuard app, however as it makes use of a local VPN, so that using a another VPN at the same time becomes impossible. That's why I'd prefer to above described enhancement. :)

**Comment by vzlcn0** [comment]
[AFWall](https://github.com/ukanth/afwall) is one option

**Comment by ericschdt** [comment]
> [AFWall](https://github.com/ukanth/afwall) is one option

There's no root access on GrapheneOS, which is required by AfWall+.

**Comment by vzlcn0** [comment]
I did not dig deep on the project, but from the documentation it need access to iptables.

It can added as system/network app and modify the sepolicy to allow it to access the iptables without root.

or create a network privilege services to wrap the app commands to iptables.

**Comment by thestinger** [comment]
@vzlcn0 The VPN service feature already provides the functionality of routing traffic through apps. NetGuard provides a firewall based on that feature and has support for forwarding traffic to a proxy/VPN from there.

**Comment by thestinger** [comment]
> so that using a another VPN at the same time becomes impossible

That's not accurate. It has support for forwarding to one. The other proxy / VPN needs to provide support for it.

**Comment by thestinger** [comment]
@vzlcn0 Giving an app access to iptables doesn't make sense and isn't how privilege separation is done for firewall configuration. The use of iptables is an implementation detail handled by netd, which exposes high-level APIs to the rest of the OS with appropriate permission checks on them.

**Comment by thestinger** [comment]
> The current firewall implementation to controll apps' traffic has pretty basic functionality: Block / Allow.

That's not really a firewall feature. It's a permission with both a low-level implementation taking away network access via kernel-level filtering (not via netfilter) and taking away high-level access through APIs via permission checks of the INTERNET permission. A firewall alone cannot provide this. It would be missing blocking access via IPC APIs including DownloadManager and others. Third party apps can also provide APIs and gate access based on the INTERNET permission. In order for filtering traffic at a socket level to work, blocking access via APIs requiring the INTERNET permission still has to be done, which is why firewalls can't really work alone.

> * Logging of incoming/outgoing traffic and its status

There's no chance that we're going to be doing deep packet inspection or performing a MITM on encrypted traffic via a local CA. We're not going to be making extra network requests to get PTR records, etc. either (reducing privacy) and those are not reliable. PTR records can claim whatever they want. The only thing we could log are IP addresses. I don't think that's particularly useful, and I'd rather leave this kind of thing to third party apps..

> * Blocking/Allowing an IP range
>     * This would allow to restrict apps eg to only the lan (useful for eg smart home apps)

Since the permission is simply `INTERNET`,  filtering on a per-app basis with a firewall doesn't work. The only way to make it work is making the `INTERNET` permission checks fail to only allow direct socket access. This is probably going to confuse users, since whether an app performs the access directly or uses an API like DownloadManager is an implementation detail. For DownloadManager, since it's provided by the OS, we could bolt on the same filtering to it. However, that makes things a lot more complicated and it's far from the only API. It doesn't do anything to address APIs provided by third party apps within the profile.

Allowing access only to local IPs will not mean that an app cannot use that to send traffic remotely. Users do not have a proper mental model about how networks work and these kinds of features will provide a false sense of security. If an app can send data via the network, even just to the local network, it should really just be assumed it can send traffic anywhere. Trusting networks and trying to build a mental model based on assumptions about other devices on the network and the router is a recipe for having a false sense of privacy and security.

> * Filter lists of predefined IPs/DNS entries to be blocked for all apps

IP addresses regularly change hands and trying to use them to enumerate badness leads to breakage. Anything like this needs to provide insight into what's happening to the user. It needs to make them aware which traffic they're blocking so that when they break an app like the update client, they aren't going to miss security updates and then end up blaming it on the OS. We have a lot of experience with needing to help people debug problems caused by filtering traffic. A low-level firewall will not provide the necessary insight into what's being blocked.

IP blacklisting is also not at all scalable with IPv6. It's becoming even less practical than it was before.

I don't think this is something we want to do. It's questionable whether we even want to provide domain-based blacklisting.

In general, these things are better left to third party apps. We'll focus on adding support for enforcing the Network (INTERNET) permission for Vanadium and keeping an eye out for other leaks in the base system.

**Comment by ericschdt** [comment]
@thestinger  Thank you very much for the detailed explanation! :) 


Just one addtional comment

>NetGuard provides a firewall based on that feature and has support for forwarding traffic to a proxy/VPN from there

That's true, however 
https://github.com/M66B/NetGuard/blob/master/FAQ.md#user-content-faq2
> NetGuard is a firewall application, so there is no intention to add VPN support. However, NetGuard supports a SOCKS5 proxy to chain VPN applications.

I am not aware of any VPN app which supports SOCKS5 proxy chaining.

**Comment by thestinger** [comment]
You could use it with Orbot. I'd recommend requesting that other VPN apps add support for it. One thing to watch out for is that other apps could potentially connect to them too. I'm not sure that their current implementation is a wise way to design it. This is certainly something that *can* be done by third party apps though, even if they don't currently do it (properly, at least).

**Comment by thestinger** [comment]
You could use it with Orbot. I'd recommend requesting that other VPN apps add support for it. One thing to watch out for is that other apps could potentially connect to them too so you should probably use authentication (assuming it's supported). I'm not sure that their current implementation is a wise way to design it. This is certainly something that can be done by third party apps though, even if they don't currently do it (properly, at least).

**Comment by vzlcn0** [comment]
> @vzlcn0 Giving an app access to iptables doesn't make sense and isn't how privilege separation is done for firewall configuration. The use of iptables is an implementation detail handled by netd, which exposes high-level APIs to the rest of the OS with appropriate permission checks on them.

You're right, I was not clear, I meant something like the [NetUtilsWrapper](https://github.com/GrapheneOS/platform_system_netd/blob/11/netutils_wrappers/NetUtilsWrapper-1.0.cpp) which vendors use it to access the netd iptables.

**Comment by dznsm** [comment]
As a related note AOSP does have a built in network logging feature thats made available for managed devices.
I imagine this could be exposed without needing device policy control - as with the feature for logging out of secondary user profiles.
Would also need an app for viewing the logs. https://developer.android.com/work/dpc/logging

**Comment by ignoramous** [comment]
DPC is severely limited to the point of being a joke (in light of other serious well thought out comments @thestinger has made on the topic):

> Apps issuing system calls directly to communicate aren't logged. Remember, UDP networking isn't logged so some media streaming, messaging, and gaming apps might not appear in the logs.
...
> Your DPC can't retrieve network logs if the device has any unaffiliated secondary users or work profiles. While waiting for new users to become affiliated, the system discards logs once the internal buffer is full. 
...
> While DNS lookups can help IT admins track network connections (see below), network logging isn't a general-purpose DNS recording solution. Here are some DNS tasks an app might do that aren't logged:
> 
> 1. Communicating directly with a DNS name server.
> 2. Calling a Java DNS library to make DNS queries.
> 3. Avoiding a DNS query by connecting to a fixed IP address.

**Comment by ignoramous** [comment]
> > @vzlcn0 Giving an app access to iptables doesn't make sense and isn't how privilege separation is done for firewall configuration. The use of iptables is an implementation detail handled by netd, which exposes high-level APIs to the rest of the OS with appropriate permission checks on them.
> 
> You're right, I was not clear, I meant something like the [NetUtilsWrapper](https://github.com/GrapheneOS/platform_system_netd/blob/11/netutils_wrappers/NetUtilsWrapper-1.0.cpp) which vendors use it to access the netd iptables.

Hypothetically, how would an app (without relying on hidden APIs) access `netd`, given approp sepolicies are set? By simply exec'ing  commands?

Another valid strategy could be to build such a firewall app (with approp sepolicies set) along with the rest of GrapheneOS (like how Android Settings app is built, for instance).

**Comment by thestinger** [comment]
I suggest reading https://twitter.com/GrapheneOS/status/1356400290640125952 and other information that's available.

This is misguided.

**Comment by ignoramous** [comment]
Thanks.

Increasingly, I think allow-lists is the way forward: Only allow connections to IPs and domains in the allow-list, deny all others.

Per-app boundaries aren't well-defined like you pointed out, Daniel, due to IPC (DownloadManager APIs as an example), but not all apps are adversarial: Folks also mean to keep their regular apps using regular APIs in-check.

**Comment by thestinger** [comment]
Doesn't work as explained in https://twitter.com/GrapheneOS/status/1356400290640125952 since they can communicate with any authoritative DNS server including their own via DNS queries to your DNS provider through the normal DNS APIs.

**Comment by thestinger** [comment]
It's not just because of IPC. It doesn't work as explained in https://twitter.com/GrapheneOS/status/1356400290640125952 since they can communicate with any authoritative DNS server including their own via DNS queries to your DNS provider through the normal DNS APIs.

**Comment by thestinger** [comment]
An app makes it query to <data>.abc.example.com and that makes a query via your DNS provider to the example.com authoritative DNS server chosen by example.com. Any app with the ability to make DNS queries can exfiltrate data via DNS. It can also obtain results back from the DNS server based on what it submitted. It's 2-way communication with any party simply from having the ability to make DNS queries via your DNS provider. That's what's explained in that thread. The entire concept of fine-grained filtering based on domains/addresses does not really work. This is just one reason.

**Comment by ignoramous** [comment]
> Any app with the ability to make DNS queries can exfiltrate data via DNS.

Most certainly, here's a case in point with a code-base I've worked in the past: [Choir Metrics](https://github.com/Jigsaw-Code/choir).

My point was: Just because certificate pinning wasn't widely deployed, it did not stop making sense to do TLS anyway; or now that [frida.re](https://frida.re/) can bypass cert-pinning, it doesn't mean TLS and apk-signing are useless... different threat models.

I see now what you're trying to say, Daniel: Most folk's threat models aren't as stringent, though, GrapheneOS, especially with you as its lead, has very high standards where misleading users into false sense of security is worse and not better :)

**Comment by thestinger** [comment]
> My point was: Just because certificate pinning wasn't widely deployed, it did not stop making sense to do TLS anyway; or now that frida.re can bypass cert-pinning, it doesn't mean TLS and apk-signing are useless... different threat models.

These comparisons don't make sense. TLS works without certificate pinning and that's not a certificate pinning bypass but rather using a modified app...

**Comment by git70** [comment]
Please, sign your function.
Maybe at least one VPN application will do it well! 
https://github.com/ProtonVPN/android-app/issues/42
