### ISSUE TITLE
 constify JNINativeMethod table -> conscrypt

### ISSUE THREAD

**Issue by vzlcn0** [GrapheneOS/os_issue_tracker#390]
Do we need to this commit in 11 ?

https://github.com/GrapheneOS/platform_external_conscrypt/commit/b8afb8af3773d630550354bd3da95da947fbb81e

**Comment by thestinger** [comment]
It was supposed to be ported over and I've added it back. It doesn't really matter though. There would need to be orders of magnitudes more work on this for it to make any real difference, and it doesn't seem like a worthwhile approach. This portion of the constification changes was kept because it's low effort and easy to maintain.
