### ISSUE TITLE
DevOps: Add Static Analysis to repository workflows in GitHub Actions

### ISSUE THREAD

**Issue by flawedworld** [GrapheneOS/os_issue_tracker#392]
Tools such as SonarCloud (https://sonarcloud.io) and GitHub CodeQL (https://github.com/github/codeql-action) are freely usable for open source projects and are quick and easy to setup as GitHub Actions. Could well be worth adding to projects such as Auditor or Attestation Server to catch bugs and help with code review.

**Comment by thestinger** [comment]
I added the gradle build process as a GitHub workflow to PDF Viewer, Auditor and AttestationServer. I don't think I want to add these static analysis tools specifically for GitHub. Further checks should be added as part of the standard build process rather than anything specific to GitHub. GitHub is now running the standard lint checks, etc. and we can choose what we want to make into errors.
