### ISSUE TITLE
Make applications ask for network permission

### ISSUE THREAD

**Issue by okeyp** [GrapheneOS/os_issue_tracker#422]
Hi, thanks for the great OS, I donated via Paypal one week ago or so :) Do you think it would be possible to make applications ask for network permission ? From what I've seen, any application could have network access without asking for it in the first place, I think this is a threat to security/privacy because any malicious application (or a malicious update from a legitimate app), could begin exfiltrating data without the user even knowing that the application is using the network, unless specifically looking for it in the settings.

**Comment by thestinger** [comment]
No, it works this way for a reason. You have the option to disable Network access before the app can run. This is not a standard runtime permission so apps don't have code to request it as needed.

Apps do not have user data entered into them by default, don't have permissions for bulk data access without asking for them and don't have access to files in the user's home directory without them granting access. They also can't run code until they're launched once since they start in the STOPPED state.

**Comment by thestinger** [comment]
We are not in a position to tell app developers how to write their code. Android adds new restrictions for new API levels and apps have to adapt to that. GrapheneOS isn't in a position to make app developers write code to check for a new runtime permission and request it.

**Comment by BayLee4** [comment]
Mhhh I'm not quite sure to understand your reasoning, if I disable network access before running the application, what difference is that with having it disabled by default ? If you think that it may breaks applications without the user knowing why, which I perfectly understand, at least give an option to enable it for advanced users. I don't see any real problem there. 

And you seems to imply that each time an application is downloaded, and each time an application is updated, then the user could always go in the settings to check that it doesn't have that network permission. This is not realistically doable. Imagine that you've installed a custom keyboard, do you really think it's a viable approach to check each updates to see if there's now network permission ? Or a SMS app ? Or whatever is crucial to privacy ?

If I'm not mistaken, it was even the default before Google decided to roll-back on that point, because users were complaining that most of applications were asking for it, even applications like calculator. 

So I don't see any strong reason not to at least give an option to re-make it the default, at least, with the informations you provided.

**Comment by BayLee4** [comment]
Mhhh I'm not quite sure to understand your reasoning, if I disable network access before running the application, what difference is that with having it disabled by default ? If you think that it may breaks applications without the user knowing why, which I perfectly understand, at least give an option to enable it for advanced users. I don't see any real problem there. 

And you seems to imply that each time an application is downloaded, and each time an application is updated, then the user could always go in the settings to check that it doesn't have that network permission. This is not realistically doable. Imagine that you've installed a custom keyboard, do you really think it's a viable approach to check each updates to see if there's now network permission ? Or a SMS app ? Or whatever is crucial to privacy ?

If I'm not mistaken, it was even the default before Google decided to roll-back on that point, because users were complaining that most of applications were asking for it, even applications like calculator. 

So I don't see any strong reason not to at least give an option to re-make it the default, at least, with the informations you provided.

**Comment by thestinger** [comment]
> Mhhh I'm not quite sure to understand your reasoning, if I disable network access before running the application, what difference is that with having it disabled by default ? If you think that it may breaks applications without the user knowing why, which I perfectly understand, at least give an option to enable it for advanced users. I don't see any real problem there.

You're welcome to implement a toggle and then to help port it to each new major release. I'll be waiting for your pull request. The default cannot be changed or app compatibility will be completely broken. GrapheneOS will fail a huge number of CTS tests and will be far less usable. Apps are not written for a platform with INTERNET as a runtime permission. They do not have code to request it and can't necessarily handle not having it available in a reasonable way. It does more than just making their connections fail. It stops them binding to a socket, communicating with other apps via localhost, etc. It still has to be granted by default to system apps regardless of the state of the toggle or the OS is going to be completely broken by default.

> And you seems to imply that each time an application is downloaded, and each time an application is updated, then the user would always have to go in the settings to check that it still doesn't have that network permission. This is not realistically doable. Imagine that you've installed a custom keyboard, do you really think it's a viable approach to check each updates to see if there's now network permission granted ? Or a SMS app ? Or whatever is crucial to privacy ?

Most applications already request it in the first place. You can check BEFORE installing the app rather than afterwards. You're free to force stop the app before upgrading it.

I think you're drastically overestimating the benefits of the permission, misunderstanding the app sandbox and permission model along with not realizing there are other ways to leak / exfiltrate data *including* via the network without having any form of direct direct access or the ability to call APIs requiring INTERNET. If you're giving apps more data and access to data (including permissions) because you can disable the Network permission, that's a huge mistake, and you're not looking at the full picture.

> If I'm not mistaken, it was even the default before Google decided to roll-back on that point, because users were complaining that most of applications were asking for it, even applications like calculator.

That was never the case. INTERNET was never a runtime permission in AOSP. Apps have never known how to request it or handle not having it.

> So with the informations you provided, I don't see any strong reason not to at least give an option to re-make it the default.

Okay, get to work on it if you want the feature.

**Comment by BayLee4** [comment]
> You're welcome to implement a toggle and then to help port it to each new major release. I'll be waiting for your pull request.

I'll try. In that regards, would you mind reopening the issue then ? I guess you can keep the 'invalid' label, it should be fine.

> The default cannot be changed or app compatibility will be completely broken. [...] It still has to be granted by default to system apps regardless of the state of the toggle or the OS is going to be completely broken by default.

Understable.

> Most applications already request it in the first place. 

I guess we don't have the same applications on our respective phones, not only one of mine asked for it first. 

> You can check BEFORE installing the app rather than afterwards. You're free to force stop the app before upgrading it.

But how convenient is that ? Force stop every applications that needs an update, and then inspecting each of them separately ? I think we can agree on the fact that a toggle is a far more convenient option. 

> I think you're drastically overestimating the benefits of the permission, misunderstanding the app sandbox and permission model along with not realizing there are other ways to leak / exfiltrate data including via the network without having any form of direct direct access or the ability to call APIs requiring INTERNET. If you're giving apps more data and access to data (including permissions) because you can disable the Network permission, that's a huge mistake, and you're not looking at the full picture.

This is the most interesting part, may I ask what is the full picture then ? Do I wrongly assume that disabling the network permission for a keyboard application prevents it from sending all my keystrokes to a remote server ? Why app sandboxing would have anything to do with that ?

Just a note, I think your misunderstanding my behaviour regarding applications, I try to keep the bare minimum of applications, preferably use an open-source F-droid alternative, and if possible I would always prefer keeping OS default applications. But the default messaging application (to name just this one), is too 'basic' not to be replaced : don't follow system dark mode, annoying emoji button instead of new line key, no ability to search in messages, etc. I don't see any 'huge mistake' in that kind of global behaviour.

> That was never the case. INTERNET was never a runtime permission in AOSP. Apps have never known how to request it or handle not having it.

Then I was mistaken, after looking a second time to that info, it seems that it was just Google Play removing a warning on network access when installing applications, so nothing to do with runtime permission, thanks for the correction.

> Okay, get to work on it if you want the feature.

I will, any kind advice on where to look preferentially in the code ? I'm not too optimistic regarding my chance of success, but I'll work on it.

**Comment by thestinger** [comment]
> I guess we don't have the same applications on our respective phones, none of mine asked for it first.

That's what I'm talking about. Apps don't know how to handle Network as a runtime permission.

> This is the most interesting part, may I ask what is the full picture then ? Do I wrongly assume that disabling the network permission for a keyboard application prevents it from sending all my keystrokes to a remote server ? Why app sandboxing would have anything to do with that ? What are the other ways you're mentioning ?

It could send the data to another app in the same profile instead, and that's inherently not possible to stop since it's the keyboard and requires communication with other apps to function.

> So I was mistaken, after looking a second time to that info, it seems that it was just Google Play removing a warning on network access when installing applications, so nothing to do with runtime permission, thanks for the correction.

They didn't ever do that either. What they did is not showing non-dangerous permissions. Dangerous permissions are the runtime permissions. INTERNET isn't a runtime permission in Android since it doesn't allow access to sensitive data which is what they use to determine if something is a dangerous permission.

**Comment by BayLee4** [comment]
> It could send the data to another app in the same profile instead, and that's inherently not possible to stop since it's the keyboard and requires communication with other apps to function.

Then why bother with (network) permission at all, if an app only need to communicate with another one which have it to bypass that restriction ? Isn't that useless and broken by design ?

**Comment by thestinger** [comment]
No, just as any other permission isn't inherently broken. Apps can communicate with mutual consent within a user profile.

**Comment by thestinger** [comment]
The reasoning that not giving an app network access prevents data exfiltration is wrong for *multiple* reasons. It can play audio, it can store data anywhere that you've given it access and it can communicate with other apps in the same user profile if they permit it. Not having network access does not mean trusting it with any data is sensible.

We're already concerned that it's a mistake to provide the Network toggle at all because users have poor reasoning about what it provides and end up giving apps sensitive data.

**Comment by thestinger** [comment]
If you give an app bulk access to contacts, as another example, it could send all of that information to another app in the user profile. It could also write data to contacts as another way of sharing data with other apps beyond mutually consenting to exchanging intents. I think you're just no reasoning about permissions correctly. In general, permissions are a bad model anyway. That's why permissions like bulk shared storage access are being phased out of Android to force apps to use case-by-case consent. Users don't even know / realize that the case-by-case approach exists due to most apps ignoring it and requesting bulk access instead, with no fallback for not granting it.

**Comment by BayLee4** [comment]
> Apps can communicate with mutual consent within a user profile.

And there is no way to track that mutual consent, so we could block it ?

**Comment by BayLee4** [comment]
> I think you're just no reasoning about permissions correctly.

You'll have to admit it's pretty fucked up : the "okay I don't have that permission so I'll ask that other app which have it, without the user knowing it nor agreeing with it", is far from any good permission design.

**Comment by thestinger** [comment]
The OS is in control of it. Apps have to list out their IPC APIs in their manifest. The receiver side can be statically analyzed. For API 30+, apps also have to list out if they explicitly query / contact other apps as opposed to launching an implicit intent handled by an available app if supported, where the user chooses which one if they are multiple.

**Comment by thestinger** [comment]
> You'll have to admit it's pretty fucked up : the "okay I don't have that permission so I'll ask that other app which have it, without the user knowing it nor agreeing with it", is far from any good permission design.

I don't know how else you would expect the system as it exists would work. Apply reasoning to it.

**Comment by BayLee4** [comment]
> I don't know how else you would expect the system as it exists would work. Apply reasoning to it.

I'm not talking about the system, I'm talking about user applications.

**Comment by thestinger** [comment]
And that's what I'm talking about.

**Comment by BayLee4** [comment]
"The system" in your sentence refers to user applications, really ?

**Comment by thestinger** [comment]
It refers to how the OS works, including the application model.

If you give apps access to any shared resource, then they can communicate without intents regardless. Network access is an example of that. Any kind of shared data or shared access to a file is another. When you share data from an app to another, that's communication between the app. When you open a URL, that's communication. When you open a file that's handled by another app, that's communication. You're constantly relying on communication between apps with profiles. You just aren't thinking about it.

**Comment by BayLee4** [comment]
That's not the point. Of course an app' could always write to a file or whatever to exfiltrate its data if it have file permission, there is no surprise there. What is a surprise, is that any app' could ask another to use a permission that was explicitly denied for itself. An by 'a permission', I mean network permission.

**Comment by thestinger** [comment]
This stuff is covered in our documentation, where we strongly encourage using user profiles as isolated workspaces.

There are numerous planned features filed on the tracker about improvements.

API 28+ removed the ability for apps to communicate without intents or shared data provided via permissions / user content by putting each app in a unique instance of the untrusted_app domain. Previously, they could set world readable / writable permissions on their own app data to allow other apps in the profile to access it.

API 30+ requires statically declaring either explicit queries or the QUERY_ALL_PACKAGES permission to permit more static analysis of app communication.

If you're not willing to think about how stuff works and reason about it, your participation here isn't productive. Calling something bad or poorly designed without thinking about what's required for it to work isn't helpful.

**Comment by thestinger** [comment]
> That's not the point. Of course an app' could always write to a file or whatever to exfiltrate its data if it have file permission, there is no surprise there. What is a surprise, is that any app' could ask another to use a permission that was explicitly denied for itself. An by 'a permission', I mean network permission.

I don't know what it is that you find surprising. Consider opening a PDF in an app. It can send whatever data it wants as part of that. That data arrives at the PDF viewer. If the PDF viewer has internet access, it can contact the internet on behalf of the app which sent the data. This applies to any kinds of file opening / sharing, or other intents. Not thinking about it this way before doesn't mean there's anything surprising about it. If you actually think through what it means that apps can open files with other apps, etc. then the conclusions from that are obvious.

**Comment by BayLee4** [comment]
Again, I am not talking about file permission. I understood your point, and that is not what I'm saying.

**Comment by thestinger** [comment]
Apps *within a user profile* can communicate with mutual consent. It's quite transparent to the end user that this happens. You know that apps can communicate with mutual consent and I'm sure you use plenty that rely on it. What do you think happens when you open a URL, file or share data from one app to another? It sends along the data. That's communication. It doesn't inherently have to send the actual kind of data that would make sense for that kind of intent.

**Comment by thestinger** [comment]
@BayLee4 I wasn't talking about any 'file permission' in that comment. Seems you're misunderstanding what I've been talking about. The storage permissions are legacy permissions. Case-by-case consent is how things are meant to be done nowadays. I'm not talking about the storage permissions for bulk access to shared storage. It's not the topic here.

**Comment by BayLee4** [comment]
> It's quite transparent to the end user that this happens. 

This. So if this is transparent, there is a way to see/control these communications right ? Earlier, you seemed to imply that it was something that can be done without the user noticing it.

**Comment by thestinger** [comment]
I strongly suggest reading out documentation and looking at the *existing* enhancements filed in the tracker. I also strongly suggest reasoning about these things and reconsidering assumptions you have about them. Consider what it means for an app to be able to open a URL, sharing data with another app, etc.

**Comment by thestinger** [comment]
> This. So if this is transparent, there is a way to see/control these communications right ? Earlier, you seemed to imply that it was something that can be done without the user noticing it.

I said it's transparent that it works this way.

**Comment by thestinger** [comment]
i.e. it's apparent from the UX that this is how it works

**Comment by thestinger** [comment]
Apps within a user profile can communicate with mutual consent. This is how the application model works. User profiles act as isolated workspaces. Apps can decide what permissions, signing keys, etc. are required to use an API that they choose to publish for other apps. This is how you're able to install an app providing a service to other apps. It's how you're able to open a URL in an app which is passed to a browser. It's how you're able to share arbitrary kinds of data between apps, including files (not talking about granting access to files in your home directory or storage providers - it's not the topic - I'm talking about opening a file in an app which then opens an app able to handle that file type).

**Comment by BayLee4** [comment]
Just to be clear, because I think we don't have the same signification for the word 'transparent'. Is, an SMS app or Keyboard app or whatever I don't give internet access to, able to communicate with Vanadium without me giving explicit consent ? Like clicking on a link, and seeing an 'Open on Vanadium' popup ?

**Comment by thestinger** [comment]
You brought up the example of a keyboard where the app is inherently chosen as a highly trusted app able to input data into other apps, edit fields of data, manage the clipboard, etc. Even if it couldn't send intents to other apps... it really doesn't make much difference.

**Comment by thestinger** [comment]
An app that you set as your keyboard can directly enter data into apps you open, edit their text fields and manage the clipboard.

As with any other app, it can communicate with other apps via mutual consent, but your example of a keyboard doesn't make much sense because you've granted it the ability to input data directly into apps, etc. You've made it into a highly trusted app. You're entering your passwords, etc. into it. The keyboard example is a really bad one.

**Comment by BayLee4** [comment]
> (not talking about granting access to files in your home directory or storage providers - it's not the topic - I'm talking about opening a file in an app which then opens an app able to handle that file type).

Yup, talking about file permission earlier was a mistake on my part, that's not what I meant

> The keyboard example is a really bad one.

Yes I see that now. I should have stayed with the SMS app.

**Comment by thestinger** [comment]
You can see for yourself that you can open a link in any app. Chromium chooses not to enforce the INTERNET permission for this. https://github.com/GrapheneOS/Vanadium/issues/37 is already filed about requiring it. Please look at the existing documentation (including for the Network toggle) and documentation in the tracker.

Also, forbidding user installed apps from communicating without another toggle (or complex toggles for every combination of user installed apps) would not change this case since it isn't one.

**Comment by thestinger** [comment]
An SMS app can send and receive SMS so it essentially has network access.

**Comment by BayLee4** [comment]
> An SMS app can send and receive SMS so it essentially has network access.

You're right, but you clearly missed the point of the question. Could, yes or no, an app use another one without at least showing a popup, or something that would made the user aware of that it will communicate with it ?

**Comment by BayLee4** [comment]
Like an 'Open this PDF with : XXX application'

**Comment by thestinger** [comment]
You can see for yourself that they can by clicking a link or countless other things you do in your every day usage. I've answered above in detail multiple times.

**Comment by thestinger** [comment]
Apps within a user profile can communicate with mutual consent. The UX would be much different if that was not the case. There are issues filed in our trackers about enhancements related to added permission checks (see the Vanadium issue) and control over communication between user-installed apps (which Vanadium isn't).

**Comment by thestinger** [comment]
I don't think this is productive or on-topic for this thread.

**Comment by BayLee4** [comment]
It is, because in that case the '[talking about bypassing network restriction] It could send the data to another app in the same profile instead' is invalid, as any user could be aware that an app will communicate with another, and denying it. If it happens without user consent, then it's valid, and in my opinion a security issue.

**Comment by thestinger** [comment]
Nothing about it is specific to this permission. It applies to any other kind of entered data or data access. Issue tracker threads should be limited to discussion about the issue at hand.

**Comment by thestinger** [comment]
There are already other enhancements filed about that topic. It doesn't belong here, and doesn't belong in a new issue about this topic. This issue is invalid because it's not in our power to do what it's requesting.

**Comment by BayLee4** [comment]
You're free to think that it's invalid, and I'm free to think that it's not, but you still didn't answered clearly to the last question, which I asked multiple times.

**Comment by thestinger** [comment]
Cannot file an issue here asking for an app like Signal to request our added Network runtime permission. You would have to file that for Signal and they aren't going to do it. Please don't bother app developers about this or you're just going to make them hostile towards GrapheneOS. It does not appear you want to talk about what was actually filed here. Please go to the appropriate threads on the tracker for those topics, or file a new one if there isn't one already. There is an issue on this tracker with a proposed alternative to needing user profiles for this. There's an issue on the Vanadium tracker about requiring INTERNET.

**Comment by thestinger** [comment]
@BayLee4 I did clearly answer it multiple times.

**Comment by thestinger** [comment]
Discussion should take place on issues where it is on-topic. This issue's topic is about making apps request the Network permission which is not something in our power to implement. It was closed for that reason. If you want to file an issue about having the option of Sensors and Network being disabled by default for user installed apps, and there isn't one already filed on the tracker, then it makes sense to file that. It doesn't belong here. Neither does discussion of further restrictions for app communication within profiles. It belongs in the existing issues filed about our plans for it, or new ones for things that aren't covered by those - but I think it's covered well already.

You should use the GrapheneOS chat channel to have general discussions, not the issue tracker. It's not a good place to explain how things work and certainly not to try arguing about it without understanding it.

**Comment by thestinger** [comment]
https://github.com/GrapheneOS/os_issue_tracker/issues/156
