### ISSUE TITLE
Auditing GrapheneOS commits

### ISSUE THREAD

**Issue by lzunsec** [GrapheneOS/os_issue_tracker#427]
I'm intersted in auditing the modifications made by GrapheneOS team on AOSP project. For example, on `platform_frameworks_base`, I can see the point from which I think GrapheneOS made modifications: https://github.com/GrapheneOS/platform_frameworks_base/commits/11?after=18b644c926562b1531876f7d7b922fee8290d9c7+69&branch=11

Is this the first commit:

enable doze and app standby
@thestinger
thestinger committed 15 days ago

?

I couldn't find any information about the merging process. Once a new android is released, how is the process of re-merging the changes from the old release? Why there's no 10, 9, etc branches anymore?

**Comment by thestinger** [comment]
You should clone a repository, add the corresponding AOSP repository as a remote called `upstream` and fetch the tags from there. It will be clearly visible where the changes start based on the AOSP tag being marked in the log.

> Once a new android is released, how is the process of re-merging the changes from the old release?

The patches are rebased (reapplied) on top of the latest upstream code. The changes to AOSP repositories are maintained as patch sets that are regularly cleaned up, reordered, etc. as expected for downstream code that's kept in shape for submission upstream and regular porting to new releases of the upstream code.

Keep in mind that GrapheneOS is not based on AOSP master. It's based on the latest stable release of AOSP. It's ported to a new stable release every month, and those are not simply advancing tags on a single stable branch. They move to new branches (quarterly releases, etc.). Every year, there's a new major OS release.

> Why there's no 10, 9, etc branches anymore?

The tags are the long-term archive of the history. The numbered branches are for the actively developed code and for forks of upstream repositories the code is maintained as a patch set that's regularly rebased.

**Comment by thestinger** [comment]
In the future, please ask questions on the #grapheneos Matrix / IRC channel.

**Comment by thestinger** [comment]
Our own projects like Auditor and hardened_malloc have a linear history (no merges) of commits with the long-term history.

For forks of AOSP repository, the development branch is the latest revision of our patch set applied to the repository. It doesn't make sense to keep old development branches. They don't have long-term history in them. They're the workspace for making the next release.

It probably makes more sense to review the most recent stable tag than the actively developed code in the development branch.

Our patches applied on top of AOSP are a linear set of commits that are kept clean by regularly rebasing to put them in a sensible order, split into a sensible set of commits. Sometimes, we split out independent changes in a sensible way. Usually, what's happening is squashing fixes. Our changes are treated as a downstream branch with patches that are ready to apply upstream. That's quite important since every month we're porting to a new stable tag which can be a new quarterly release or major yearly release. It's crucial for the patches to be kept in good shape. We have to deal with reviewing porting on a monthly basis. Keep in mind we're based on stable releases of AOSP, not the development branch. The new stable releases of AOSP are not simply extra commits to the previous ones. They're tags on branches for developing stable releases and there are multiple concurrent branches for each major release.

**Comment by thestinger** [comment]
Our own projects like Auditor and hardened_malloc have a linear history (no merges) of commits with the long-term history.

For forks of AOSP repository, the development branch is the latest revision of our patch set applied to the repository. It doesn't make sense to keep old development branches. They don't have long-term history in them. They're the workspace for making the next release.

It probably makes more sense to review the most recent stable tag than the actively developed code in the development branch.

Our patches applied on top of AOSP are a linear set of commits that are kept clean by regularly rebasing to put them in a sensible order, split into a sensible set of commits. Sometimes, we split out independent changes in a sensible way. Usually, what's happening is squashing improvements. Our changes are treated as a downstream branch with patches that are ready to apply upstream. That's quite important since every month we're porting to a new stable tag which can be a new quarterly release or major yearly release. It's crucial for the patches to be kept in good shape. We have to deal with reviewing porting on a monthly basis. Keep in mind we're based on stable releases of AOSP, not the development branch. The new stable releases of AOSP are not simply extra commits to the previous ones. They're tags on branches for developing stable releases and there are multiple concurrent branches for each major release.

**Comment by ypid** [comment]
Sorry for posting in a closed question, but I think I have something that can help (not very polished yet): https://github.com/ypid/android-review

**Comment by lucaszanella** [comment]
@ypid this is very useful, gonna read carefully in the future, thank you
