### ISSUE TITLE
Alarms of Clock app are not yet completely reliable with RQ1A.210105.002.2021.01.23.03

### ISSUE THREAD

**Issue by Saroumane** [GrapheneOS/os_issue_tracker#430]
**Setup**

Device : Pixel 3a
Build RQ1A.210105.002.2021.01.23.03

**Use case**

I noticed that sometimes one alarm did not ring when I have 2 alarms following each other, so I decided yesterday to erase  and recreate them for this morning : 
- 1st alarm : 07:30, name "A1", repeat : "every weekday except Saturday and Sunday",  ring : "(default platinum)", vibrate "yes"
- 2st alarm : 07:35, name "A2" repeat : "every weekday except Saturday and Sunday",  ring : "(default platinum)", vibrate "yes"

**What happened :** 
I had another device to wake me up before 07:30 and I noticed that :
- 1st alarm rang precisely at 07:34 (4 minutes too late) (I got up and disabled the 2nd alarm before 7:35)

**Comment by beerisgood** [comment]
Did you reset Clock app?
In the past some changes are made which should solve such issues.

**Comment by Saroumane** [comment]
I rebooted the whole phone today, I guess it's the same ?
If the workaround is to reset Clock app every day, well...

**Comment by beerisgood** [comment]
Rebooting doesn't clear any app data.
You need doing that manually.

**Comment by Saroumane** [comment]
Ok. As there is no "reset", I did a "Force stop". And started manually the app.

**Comment by beerisgood** [comment]
That doesn't solve your problem.
You need clear app data in the same window you force stop the app.

**Comment by Saroumane** [comment]
![signal-2021-01-28-201321](https://user-images.githubusercontent.com/22261137/106187085-70820780-61a5-11eb-914c-231b144c14af.png)

**Comment by beerisgood** [comment]
Yes, clear storage will reset the app which should fix your problem.
You can reboot after if you want but it shouldn't be required.

Your alarms need to be configured then again.

**Comment by thestinger** [comment]
We essentially updated to a newer revision of the AOSP app and clearing data is a good idea to have the new changes fully activated. Make sure that the app is shown as having a battery optimization exception. It's granted that by default but maybe you somehow didn't get that.  The alarm ringing 4 minutes late sounds like the typical situation where power optimization delays alarms in order to run more stuff together. That's avoided by using 'exact' variants of the APIs and getting an exception from the power optimization rules.

I don't think there's going to be a way to debug this if you've already cleared your data now, and regardless, this is not an app that we actually develop and we aren't familiar with it. It's an AOSP app. The most we'd actually do is updating to an even newer revision from AOSP master which will definitely come with new issues even if it fixes something. AOSP master isn't stable.

**Comment by Saroumane** [comment]
Thanks for the explanations.
For the record, Clock app has now "Background restriction : Background usage can't be restricted" and "Battery optimization : Not optimized + Battery optimization not available"
I don't remember the values before clearing storage.

I must confess that knowing the AOSP code used for GrapheneOS is not considered as "stable" is a bit disturbing.
Maybe it should be added to https://grapheneos.org/ main page, or faq ?
In fact, the only use of the word "stable" in the faq says quite the opposite :
_Releases for each supported device need to be robust and stable, with all standard functionality working properly and testing for each of the releases._

**Comment by thestinger** [comment]
> I must confess that knowing the AOSP code used for GrapheneOS is not considered as "stable" is a bit disturbing.

That's not what I said. I said that AOSP master is not considered stable. That's not what we use, and that's why we don't want to update to some arbitrary revision of AOSP master to get a newer version of the clock.

**Comment by thestinger** [comment]
GrapheneOS is based on the latest stable release of AOSP. We don't want to pull in newer unstable versions of the apps from AOSP master to get improvements. I'm interpreting what you're doing now as concern trolling because you aren't happy with the answer.

**Comment by Saroumane** [comment]
Not at all, I misunderstood a " **'d** " for **had**,  whereas I understand now it was a "**would**". As you may have noticed, I am not a native english speaker.
Daniel, I have the deepest respect for your work. I already donated for this project and will again in the future.
