### ISSUE TITLE
No LTE (only 3G) on Sprint Network Android

### ISSUE THREAD

**Issue by MJS123456789** [GrapheneOS/os_issue_tracker#441]
I cannot access Sprint LTE network in GrapheneOS on Pixel 3  Voice and 3G does work.  Also tapping Carrier settings does not pull up menu, and Visual voicemail does not download.  Reddit Research indicates this may be a new issue not present on Android 10.

**Comment by thestinger** [comment]
You should move to the proper T-Mobile carrier. Sprint is a legacy carrier and requires invasive carrier apps to function properly.

**Comment by thestinger** [comment]
These problems are largely unique to the US and specifically Sprint. Google Fi is the only other extremely problematic carrier as far as we know.

**Comment by thestinger** [comment]
These problems are largely unique to the US and specifically Sprint. There is no way of this ever being resolved now because it's being rapidly phased out after being purchased by T-Mobile. T-Mobile itself works extremely well with GrapheneOS. Most carriers work well. I don't know what the timeline is for Sprint being completely gone but that will be nice. I don't think we'll be specifically documenting it as unsupported due to it being obsolete.
