### ISSUE TITLE
grapheneOS has been freezing lately on pixel 4

### ISSUE THREAD

**Issue by modernNeo** [GrapheneOS/os_issue_tracker#442]
started maybe 2-4 weeks ago. would keep happening when I was scrolling i.reddit.com using the tor browser. the screen would become unresponsive and time would not update, I once waited like 3-4 minutes but it just stayed frozen and I had to do a hard reboot to get it responsive again. I had assumed that maybe the tor browser was causing the issue so I switched back to firefox.

but it also happens on firefox too.

**Comment by sempervictus** [comment]
I have not observed this behavior. happen to have links to those reddit pages causing the lockup? There might be something "fun" in there not visible to the human eye but ultimately ineffective against the hardening mechanisms applied here.

**Comment by modernNeo** [comment]
its pretty random reddit links. I think it just happens when I browse reddit cause its one of the only website I browse on mobile.

I am unsure if there is a way to provide logs to indicate what is happening in the back-end since I realize that my issue has so little information to go on.

But I will say the error does not always happen. its somewhat intermittent. Sometimes I can browse for 10 mins and not have anything happen, and sometimes it does not happen at all.

**Comment by anupritaisno1** [comment]
Related? https://github.com/GrapheneOS/os_issue_tracker/issues/451

**Comment by thestinger** [comment]
There's no way that's related. It's an optimization.

**Comment by thestinger** [comment]
It's also configuration specific to the JIT, so we don't use it.

**Comment by modernNeo** [comment]
I **think** the issue may be because of the ExpressVPN app I have on my phone. I have removed it for the time being and will give it a week or 2 to see if the issue happens again. I don't know if this issue needs to be closed while I see if ExpressVPN is the real culprit.

**Comment by renlord** [comment]
This might be related to SystemUI freezing which also happens across other phone models too.
I also personally experienced this.

**Comment by modernNeo** [comment]
I encountered this issue again last night. although this time, for the first time, I got the pop-up "System UI isn't responding" after it being frozen for like a min or so.

Is there any way to collect logs immediately after this happens so that the devs have more to go on to diagnose this?

**Comment by darktelco** [comment]
Pixel 4, latest stable build.  Cannot reproduce.  Please provide some links to test.

**Comment by modernNeo** [comment]
I just go on i.reddit.com on my phone but it happens intermittently Sometimes its after I have been browsing reddit for 20 mins or sometimes for 2 mins.

**Comment by hanzano** [comment]
I can fairly easy reproduce that:

1. Reboot the device (just to get a "clean" state)
2. Open Firefox Browser (v86.1.1)
3. Visit https://signalstickers.com/
4. Scroll to the bottom multiple times in order to let Firefox load more and more stickers
5. Click on some animated stickers. Just browse into different animated sticker subpages.

-> Firefox becomes sluggish and 2 seconds later, the whole system hangs.

Yesterday I listened to music with VLC while browsing the stickers. This made the whole system hang for 2 minutes (of course music stops playing then).

I never had this with any other app than Firefox (and TOR Browser of course) up until now.

I am on Pixel 3a, latest stable GrapheneOS.

**Comment by LunchBoxStevieC** [comment]
I'm having the same issue on my Pixel 5.  Randomly it freezes and then comes back.

**Comment by thestinger** [comment]
Please test this on the latest https://grapheneos.org/releases#2021.03.19.14 release. It's *possible* that the larger address space alleviates it, but I doubt it. I expect that the actual cause of these issues are upstream bugs being uncovered by our hardening features. I'm unable to replicate it on any device, and so far another developer hasn't stepped up to figure out what's happening.

**Comment by thestinger** [comment]
It's quite possible that it's not a single issue, but rather sometimes hardened_malloc uncovers a memory corruption bug in the upstream code and the OS may handle System UI dying poorly. It's really not clear what's going on since no one has provided any useful bug report zips or logs. There definitely won't be progress without at least getting that.

**Comment by LunchBoxStevieC** [comment]
I'd be glad to provide you whatever I can but I'd need some sort of step by step how to collect the data.  I'm good at following directions, just not too well versed on the universe here, it's a bit new for me running a different OS.

**Comment by thestinger** [comment]
Enable developer options and use the bug report capture tool there. Have an email client installed or a Matrix client and send it either to the daniel.micay@grapheneos.org email address or my @strcat:matrix.org handle on Matrix. It gives you a button to share it after it finishes capturing it. Use the full bug report capture option.

You need to do right after the issue is triggered. Also, ideally, it happens as soon as possible after a clean reboot with as few apps, etc. installed as possible and as few deviations from default configuration as possible.

**Comment by LunchBoxStevieC** [comment]
I can do that... Is there a way to back up my current configuration so I can return it to a stock Graphene install and run it like that until the bug happens and then restore my settings later?

**Comment by LunchBoxStevieC** [comment]
Also how would I load this on to try to see if it corrects the issue?  https://grapheneos.org/releases#2021.03.19.14

**Comment by thestinger** [comment]
You can use Seedvault to backup app and OS data in the Owner profile. Need to backup the profile's home directory manually.

**Comment by thestinger** [comment]
@LunchBoxStevieC Turn on the Beta channel in the Updater: https://grapheneos.org/usage#updates.

**Comment by thestinger** [comment]
It probably won't resolve the issue, but it's best to be testing against the latest release (which will be in the Stable channel in the next couple days anyway, assuming not major issues are identified with it, and they likely won't be).

**Comment by LunchBoxStevieC** [comment]
Ok I'll try the latest build first and if that doesn't work then back-up, restore to stock, monitor for bug and then do a capture and report back.  Again, thank you for the help.

**Comment by LunchBoxStevieC** [comment]
Ok got the Beta (2021.03.19.14) installed and running.  Will give this a go the next few days and see if the random freezing happens again.  If it does I'll proceed to back-up, revert to stock (with just e-mail setup) and then test and capture and report back.  Thanks again for the help.

**Comment by LunchBoxStevieC** [comment]
I'm happy to report that Beta (2021.03.19.14) Firmware seems to have cured the non-responsive problem.  I've really put the phone through heavy use the last couple of days and not once did it appear and it would have for sure.  I also didn't reboot the phone either for good measure.  Thanks very much!

**Comment by thestinger** [comment]
I'd guess that it has to do with either memory exhaustion or address space exhaustion (perhaps from address space fragmentation) in that case. The massive 48-bit address space alleviates any issues with address space and app compaction will save a lot of memory. We're hard at work on reducing the hardened_malloc slab quarantine memory usage drastically for the system as a whole but it's probably not going to help out System UI much based on how it's being done to avoid either giving up the massive security benefits or reducing performance further.

**Comment by LunchBoxStevieC** [comment]
I find it fine navigating around in terms of responsiveness but maybe that's because it's a Pixel 5 and not older hardware???

**Comment by thestinger** [comment]
Responsiveness, etc. isn't an issue anywhere. I'm just talking about what was happening here. Probably a resource (address space or memory) exhaustion issue.

**Comment by dznsm** [comment]
I've had this on and off for sone time. It's been mainly (possibly exclusively? ?) when I've been using Element. I know the same issue was hitting lots of people on different Androids, but the Element devs implemented a fix (and I stopped hitting it for a bit). Recently feels like the frequency I see it has been rising again.
I am in a lot of element rooms. Use it a fair bit for a few projects I'm involved with.

**Comment by thestinger** [comment]
Element freezing or the whole system UI freezing? Those are much different things and this issue is only about the system UI.

**Comment by LunchBoxStevieC** [comment]
For me it's the whole O/S like it pauses for a minute and won't respond to any actions on the screen clicked on / touched then then resumes like it was busy for a moment doing something. To be honest it's quite annoying and I temporarily took Graphene off and went back to CalyxOS to make sure it wasn't something hardware related and it's not.  It's definitely Graphene.

**Comment by thestinger** [comment]
Please don't discuss or promote projects involved in harassing GrapheneOS developers and spreading misinformation about the project here. Thanks.

**Comment by LunchBoxStevieC** [comment]
My intention was not to promote another OS, my intention was to tell you it's a problem with your OS and not my hardware.  Sorry for not going back to a Google infected OS like the standard OS and choosing "That other" OS to prove which was the problem.  Perhaps if you spent more time fixing the problems and less time attacking users who are trying to tell you there is a problem, it wouldn't exist.

**Comment by thestinger** [comment]
Recommend reading https://grapheneos.org/usage#bugs-uncovered-by-security-features. A major part of the purpose of GrapheneOS is preventing the exploitation of security bugs. This leads to latent issues being uncovered resulting in processes being aborted and needing to restart. So far, no one has provided any bug report zips or logs to work on this issue.

**Comment by thestinger** [comment]
> Sorry for not going back to a Google infected OS like the standard OS

Yet you're talking about another OS with Google apps and services bundled...

**Comment by thestinger** [comment]
> Perhaps if you spent more time fixing the problems and less time attacking users who are trying to tell you there is a problem, it wouldn't exist.

At no point were you attacked in any way. Perhaps if instead of concern trolling you actually tried to gather logs and a bug report zip, your participation here would actually be helpful. You're no longer welcome in our community including the issue tracker, Matrix, IRC, Reddit or our Twitter threads. Bye.

**Comment by LunchBoxStevieC** [comment]
I see you are a 6 year old... Wonderful.

**Comment by thestinger** [comment]
This issue is being replaced with https://github.com/GrapheneOS/os_issue_tracker/issues/531. Please do not participate in that thread unless you have something helpful to add. If you want to post about experiencing the issue, you need to send a bug report zip to contact@grapheneos.org captured after the problem occurs. Do not need further feedback without providing the necessary logs and debug info via a bug report zip for resolving the problem. We're aware that there's some kind of upstream bug being uncovered by a hardening feature. This is how GrapheneOS is intended to work.

A lot of effort has to go into narrowing down and resolving these issues. It's incredibly unhelpful to have people concern trolling and attacking the project due to it. I have put substantial time into this issue already. The way myself and other developers get treated by many of our users is incredibly disrespectful and hurtful.

@LunchBoxStevieC has been blocked from participation in the @GrapheneOS organization and will need to apologize if they want to participate here further. Responding to moderation with concern trolling and attacks on the developers / project is completely inappropriate. In hindsight, I should have been firmer in handling a previous thread involving them. I went out of the way to assume good faith but they continued the same attacks on the project and their assumption that changes we make intentionally as part of improving privacy, security, etc. are flaws rather than things working as intended.
