### ISSUE TITLE
Clock app sporadically resets

### ISSUE THREAD

**Issue by Jawshy** [GrapheneOS/os_issue_tracker#450]
### Bug description
The Clock app rarely resets losing all alarms, clocks, timers, and settings. I'll send an email to contact@grapheneos.org with a bug report. 

### Steps to reproduce
1. Don't know how to reproduce, but this has occurred more than once. 

### Device info
**Device:** Google Pixel 3a XL (aosp_bonito)
**Android version:** 11 (RQ1A.210205.004.2021.02.07.17)

**Comment by thestinger** [comment]
We're not realistically going to be able to do anything without a way to reproduce it. It's also not an app that we develop ourselves, so the most we're likely to do is update to a newer version. In the past, that has caused issues, and we prefer getting the updates when they make their way into AOSP stable releases rather than using versions of the apps from master.

**Comment by beerisgood** [comment]
@Jawshy did you reset clock app? Should fix old issues

**Comment by Jawshy** [comment]
> 
> 
> @Jawshy did you reset clock app? Should fix old issues

I can do that now and will reply if I can reproduce the issue.

**Comment by thestinger** [comment]
Any update?

**Comment by Jawshy** [comment]
No, issue hasn't yet occurred again.

**Comment by thestinger** [comment]
It was probably a problem with the old state generated by an old version of the app. It would be too hard to figure out how to handle it since we don't know which old version was the issue.
