### ISSUE TITLE
GrapheneOS SeedVault: Unable to get management intent from transport

### ISSUE THREAD

**Issue by BradNut** [GrapheneOS/os_issue_tracker#463]
While investigating why SeedVault had not run a backup since 12-12-2020 on GrapheneOS where this is implemented as the OS backup solution I found that the backup page shows a black screen and not the seed vault settings.

Device: Pixel 3a XL
GrapheneOS Build: RQ1A.210205.004.2021.02.19.15
With what I assume is the latest release of SeedVault.

SeedVault submitted issue: https://github.com/seedvault-app/seedvault/issues/213

ADB Logcat when navigating to GrapheneOS' backup screen (a full log taken here: [Logcat_seedvault_error.log](https://github.com/seedvault-app/seedvault/files/6032733/Logcat_seedvault_error.log)):
`02-23 16:22:10.950  1006  1043 I ActivityManager: Start proc 8292:com.stevesoltys.seedvault/u0a180 for service {com.stevesoltys.seedvault/com.stevesoltys.seedvault.transport.ConfigurableBackupTransportService}
02-23 16:22:12.738  8292  8292 E AndroidRuntime: Process: com.stevesoltys.seedvault, PID: 8292
02-23 16:22:12.738  8292  8292 E AndroidRuntime:        at com.stevesoltys.seedvault.metadata.MetadataManager.getMetadata(MetadataManager.kt:43)
02-23 16:22:12.738  8292  8292 E AndroidRuntime:        at com.stevesoltys.seedvault.metadata.MetadataManager.getBackupToken(MetadataManager.kt:195)
02-23 16:22:12.738  8292  8292 E AndroidRuntime:        at com.stevesoltys.seedvault.App.migrateTokenFromMetadataToSettingsManager(App.kt:102)
02-23 16:22:12.738  8292  8292 E AndroidRuntime:        at com.stevesoltys.seedvault.App.access$migrateTokenFromMetadataToSettingsManager(App.kt:37)
02-23 16:22:12.738  8292  8292 E AndroidRuntime:        at com.stevesoltys.seedvault.App$onCreate$2.invoke(App.kt:87)
02-23 16:22:12.738  8292  8292 E AndroidRuntime:        at com.stevesoltys.seedvault.App$onCreate$2.invoke(App.kt:37)
02-23 16:22:12.738  8292  8292 E AndroidRuntime:        at com.stevesoltys.seedvault.AppKt.permitDiskReads(App.kt:131)
02-23 16:22:12.738  8292  8292 E AndroidRuntime:        at com.stevesoltys.seedvault.App.onCreate(App.kt:86)
02-23 16:22:12.738  8292  8292 E AndroidRuntime:        at com.stevesoltys.seedvault.metadata.MetadataManager.getMetadata(MetadataManager.kt:40)
02-23 16:22:12.779  1006  4808 I ActivityManager: Process com.stevesoltys.seedvault (pid 8292) has died: fg  IMPF
02-23 16:22:12.780  1006  4808 W ActivityManager: Scheduling restart of crashed service com.stevesoltys.seedvault/.transport.ConfigurableBackupTransportService in 1024000ms for connection
02-23 16:22:53.439  1006  1513 E BackupManagerService: [UserID:0] Unable to get management intent from transport: Transport com.stevesoltys.seedvault.transport.ConfigurableBackupTransport not registered
02-23 16:23:38.515  1006  4931 E BackupManagerService: [UserID:0] Unable to get management intent from transport: Transport com.stevesoltys.seedvault.transport.ConfigurableBackupTransport not registered
`

A separate crash monitored here:
`
--------- beginning of crash
02-23 16:16:24.849  3857  3857 E AndroidRuntime: FATAL EXCEPTION: main
02-23 16:16:24.849  3857  3857 E AndroidRuntime: Process: com.stevesoltys.seedvault, PID: 3857
02-23 16:16:24.849  3857  3857 E AndroidRuntime: java.lang.AssertionError: Error reading metadata from cache
02-23 16:16:24.849  3857  3857 E AndroidRuntime:        at com.stevesoltys.seedvault.metadata.MetadataManager.getMetadata(MetadataManager.kt:43)
02-23 16:16:24.849  3857  3857 E AndroidRuntime:        at com.stevesoltys.seedvault.metadata.MetadataManager.getBackupToken(MetadataManager.kt:195)
02-23 16:16:24.849  3857  3857 E AndroidRuntime:        at com.stevesoltys.seedvault.App.migrateTokenFromMetadataToSettingsManager(App.kt:102)
02-23 16:16:24.849  3857  3857 E AndroidRuntime:        at com.stevesoltys.seedvault.App.access$migrateTokenFromMetadataToSettingsManager(App.kt:37)
02-23 16:16:24.849  3857  3857 E AndroidRuntime:        at com.stevesoltys.seedvault.App$onCreate$2.invoke(App.kt:87)
02-23 16:16:24.849  3857  3857 E AndroidRuntime:        at com.stevesoltys.seedvault.App$onCreate$2.invoke(App.kt:37)
02-23 16:16:24.849  3857  3857 E AndroidRuntime:        at com.stevesoltys.seedvault.AppKt.permitDiskReads(App.kt:131)
02-23 16:16:24.849  3857  3857 E AndroidRuntime:        at com.stevesoltys.seedvault.App.onCreate(App.kt:86)
02-23 16:16:24.849  3857  3857 E AndroidRuntime:        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
02-23 16:16:24.849  3857  3857 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6715)
02-23 16:16:24.849  3857  3857 E AndroidRuntime:        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
02-23 16:16:24.849  3857  3857 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
02-23 16:16:24.849  3857  3857 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
02-23 16:16:24.849  3857  3857 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
02-23 16:16:24.849  3857  3857 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7660)
02-23 16:16:24.849  3857  3857 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-23 16:16:24.849  3857  3857 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
02-23 16:16:24.849  3857  3857 E AndroidRuntime:        at com.android.internal.os.ExecInit.main(ExecInit.java:48)
02-23 16:16:24.849  3857  3857 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
02-23 16:16:24.849  3857  3857 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
02-23 16:16:24.849  3857  3857 E AndroidRuntime: Caused by: java.io.IOException
02-23 16:16:24.849  3857  3857 E AndroidRuntime:        at com.stevesoltys.seedvault.metadata.MetadataManager.getMetadata(MetadataManager.kt:40)
02-23 16:16:24.849  3857  3857 E AndroidRuntime:        ... 19 more
02-23 16:16:24.850  3857  3857 E AndroidRuntime: Error reporting crash
02-23 16:16:24.850  3857  3857 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
02-23 16:16:24.850  3857  3857 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
02-23 16:16:24.850  3857  3857 E AndroidRuntime:        at android.os.BinderProxy.transact(BinderProxy.java:550)
02-23 16:16:24.850  3857  3857 E AndroidRuntime:        at android.app.IActivityManager$Stub$Proxy.handleApplicationCrash(IActivityManager.java:5208)
02-23 16:16:24.850  3857  3857 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:158)
02-23 16:16:24.850  3857  3857 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
02-23 16:16:24.850  3857  3857 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
02-23 16:16:24.850  3857  3857 E AndroidRuntime:        at java.lang.Thread.dispatchUncaughtException(Thread.java:2203)
02-23 16:16:24.900  1006  3749 I ActivityManager: Process com.stevesoltys.seedvault (pid 3857) has died: fg  IMPF
02-23 16:16:24.901  1006  3749 W ActivityManager: Scheduling restart of crashed service com.stevesoltys.seedvault/.transport.ConfigurableBackupTransportService in 1000ms for connection
`

Images of device settings and app:
![Screenshot_20210223-132734](https://user-images.githubusercontent.com/6621295/108932295-03954c80-7641-11eb-8bf9-a28bfdddbb74.jpeg)
![Screenshot_20210223-132726](https://user-images.githubusercontent.com/6621295/108932300-07c16a00-7641-11eb-8715-ad3f23856617.jpeg)
![Screenshot_20210223-160817](https://user-images.githubusercontent.com/6621295/108932311-0b54f100-7641-11eb-9d59-414bd239c75e.jpeg)

**Comment by thestinger** [comment]
I suggest filing a Seedvault issue:

https://github.com/seedvault-app/seedvault/issues

This does not appear to be a GrapheneOS issue but rather a Seedvault one.

**Comment by Rudd-O** [comment]
Same problem on my phone:

https://gist.github.com/Rudd-O/b9220fe765c6ccc8dfac9c9c89c65659

This _may_ be a bug in Seedvault, but GOS ships the program as a **system app**, so we rely on **you** to fix it.

**Comment by Rudd-O** [comment]
https://github.com/seedvault-app/seedvault/issues/351

**Comment by Rudd-O** [comment]
Honestly I think this is an integration defect, by which I mean to say that something during the GOS build did not integrate the correct `ConfigurableBackupTransport` or something.  Thus, this may qualify as a legitimate GOS bug.

**Comment by Rudd-O** [comment]
This is truly tragic -- I am gonna have to migrate over a hundred apps one by one (**if** they can be migrated at all).  Sigh.  Just exactly when you need _this_ to work, it doesn't.

**Comment by thestinger** [comment]
The integration is simply setting a single string setting it as the backup provider: `<string name="def_backup_transport" translatable="false">com.stevesoltys.seedvault.transport.ConfigurableBackupTransport</string>`. I don't see how there could be any issues with it. It's a Seedvault issue, not a GrapheneOS one. The error you're highlighting is a symptom of a Seedvault bug rather than the problem itself which was the case with the issue above which was likely a backwards incompatible change that was made by accident. The only thing we would have done to cause that is regularly updating it.

We're aware that Seedvault is not as reliable as it would need to be in order to provide reliable backups. There have been a lot of issues with it. We're not going to be contributing upstream due to the takeover of the project by hostile people and we intend to drop it from the OS with or without a replacement available. We'll hopefully get a replacement made by the time we want to go through with dropping it. The replacement is very likely not going to be backwards compatible. That's the reality of replacing a problematic component after a hostile takeover which took it in a different direction than what we originally wanted for the app.

**Comment by thestinger** [comment]
This is a great example of why we generally go out of the way to avoid integrating any third party projects. In this case the project was created/maintained by a GrapheneOS community member and then taken over by terrible people who we have little interest in interacting with at all let alone being able to trust them with development. That's clearly not going to work out. I don't think it's ever going to be good software and we could mark it deprecated and make it clearer that we intend to replace it with something else based on lessons learned from this whole experience. 

We could consider simply forking it and fixing all of these issues along with just taking development in a different direction and making a new incompatible backup format followed by dropping the current one after a few weeks since it has differences from how we think it should be implemented.

Don't really have the resources to take on everything at once. It's going to take time to fix this mess. That's the reality of how this went down. It's another lesson in why we shouldn't be relying on other projects and people not closely tied to the GrapheneOS project. Should have seen what those people were like much earlier and avoided ended up in a situation where a hostile group makes software we use.

**Comment by quh4gko8** [comment]
How about making Seedvault disable-able as a start of phasing out Seedvault?

**Comment by Rudd-O** [comment]
I THINK that it cannot really be made disableable without removing it from the OS base image, and it can't be used as backup utility if not included in OS base image.

So it's probably just going to have to be ripped out, if it's not going to be actively maintained by a GOS community member.
