### ISSUE TITLE
Localhost in Internet connectivity check - more stealth network activity

### ISSUE THREAD

**Issue by mlario** [GrapheneOS/os_issue_tracker#499]
Thanks for your great work and effort. 

Could you please add an option of localhost in Network & internet -> Advanced -> Internet connectivity check

This way connectivity checks would be switched off (requesting from localhost) - less network activity is good. But could be easily activated to GrapheneOS option for captive portal logins if need be

This would help phone remain more stealth (while also avoiding home calling to google with Standard (Google) option), and should be a bit less unique than always pinging graphene domains

**Comment by beerisgood** [comment]
> This would help phone remain more stealth (while also avoiding home calling to google with Standard (Google) option)  

This is already solved with GrapheneOS switch which is also default.
I'm not sure about but guess using localhost wouldn't work anyway.

**Comment by thestinger** [comment]
It won't work. It would be possible to support disabling it, but it's not really going to help you blend in. You blend in by using the standard checks, otherwise it's apparent that it's a rare form of Android variant.

It will reduce hurt functionality such as switching between Wi-Fi and mobile data as needed, dealing with captive portals, detecting connectivity problems more generally, etc.

**Comment by thestinger** [comment]
Replaced this with https://github.com/GrapheneOS/os_issue_tracker/issues/500.
