### ISSUE TITLE
Supporting Marlin / Sailfish ?

### ISSUE THREAD

**Issue by jpaechnatz** [GrapheneOS/os_issue_tracker#50]
Since https://github.com/GrapheneOS/device_google_marlin is having releases ready, is there a tutorial how to use them? Google extended it's OS Support to Android Q for those devices, so does GrapheneOS support them?

Could I install the marlin variant onto my sailfish device? There is no information about installation at https://seamlessupdate.app/ so help would be very appreciated ;-)

Thanks!

**Comment by thestinger** [comment]
The page at https://seamlessupdate.app/ is a placeholder site with early preview releases. It only includes minimal installation instructions, not building instructions or other documentation. The official GrapheneOS site will be at https://grapheneos.org/ and has not been made yet.

There are no official releases for marlin or sailfish due to lack of time. They aren't currently fully supported in the sources. The presence of the device repository in the source tree doesn't mean that support for it has been completed. It would need a custom kernel and any issues specific to the device would need to be fixed or worked around. It would also require supporting the legacy approach to verified boot in the build and installation instructions. I only started on the work required to support them and I'm not currently actively working on it. I no longer have a sailfish device for testing, so it couldn't be supported.

There's no timeline for supporting them and it won't necessary ever happen. They don't meet the current standards and are an annoyance due to the quirks of the legacy verified boot implementation and lack of support for the Auditor app. Supporting them means having special cases not only in the code but also in documentation to explain how things are different on older devices.

Both of these devices share the marlin device and kernel repositories, so there would never be a sailfish device or kernel repository. The marlin device repository is also for sailfish but it being present doesn't mean that the device is supported.
