### ISSUE TITLE
sim carrier info exposed to 3rd party apps

### ISSUE THREAD

**Issue by mlario** [GrapheneOS/os_issue_tracker#501]
3rd party apps can get info about sim carrier

Found it today on GrapheneOS, also same for some other android roms

How to reproduce:

1. Install Wire or Watsapp
2. Follow to login prompt
3. Notice how those apps detect country of sim card origin and correctly set country code

I used 2 different sim cards (Germany and Belgium), when changing sim card and reinstalling apps they detect correct sim card country of origin. 

Flight mode does not stop this leak. Only deactivation of sim or removal of sim from the phone

Since most people use sims in their country of origin this leak provides general country location leak w/o requesting location in app permissions.

Also not sure if the sim identifiers are not leaked

It seems more general android problem. Was wondering if there is any way to avoid this except of removing/deactivating the sim?

Thanks

**Comment by thestinger** [comment]
See https://grapheneos.org/faq#non-hardware-identifiers. Global configuration data including timezone, locale and country code are available to apps. It's not a bug or something unexpected. Reducing the system properties available to apps is something that can be done but there has to be a specific plan.

This isn't a bug report or new discovery, but it's filed as one or as a question rather than as an enhancement issue with a clear plan. It's better to use the Matrix / IRC channel for asking questions. It would make sense to have enhancement issues filed about these things but there needs to be an actionable plan taking into account app compatibility, other ways of obtaining the information and similar forms of information (locale, timezone).

> Also not sure if the sim identifiers are not leaked

No, please read the documentation: https://grapheneos.org/faq#hardware-identifiers.

**Comment by thestinger** [comment]
Referring to carrier country code as a location leak is hyperbolic and it isn't really any more of one than locale and time zone. Browsers give your locale and time zone to every web site too. A proper enhancement issue about these topics for Vanadium and/or the OS is welcome but it really needs to take everything into account. Don't want to have non-actionable issues though and the issue tracker isn't a good place for questions or general discussion.

**Comment by thestinger** [comment]
I added further information to the section.

**Comment by mlario** [comment]
OK, thanks. Indeed should have created a proper enhancement issue
