### ISSUE TITLE
Pixel 5 - Issues (Freezing, Notifications and Haptic feedback)

### ISSUE THREAD

**Issue by LunchBoxStevieC** [GrapheneOS/os_issue_tracker#513]
Pixel 5 - Latest stable release flashed fresh.

1) Haptic Feedback for keyboard doesn't turn off when set to off with slider.

2) Random freezing in various apps and web browser.  No response, can't do anything then comes back a few seconds to a couple minutes later.  Even on fresh daily boot.

3) Not all app notifications are working.  Work around is to leave app running in background for some and others app has to be left on the screen before putting phone to sleep.   Checked power settings for the app, tried reinstalling the app as well.

**Comment by thestinger** [comment]
Need to make a separate issue for each thing and please check for existing issues first.

**Comment by Peter-Easton** [comment]
Ahoy! 

With respect to app notifications, app notifications implemented through Google Play will not function. This is due to the app being hard-coded to be dependent on Push notifications via Google Play services, which are not included in GrapheneOS by design. Some apps, such as Signal, detect handsets with missing or disabled Play Services and ask to disable battery optimizations and remain in the background, and are even optimized to run with very little power consumption. A sustainable solution to this would be to contact the application developers and encourage them to optimize their apps to run on handsets/operating systems without Play Services. There's very little GrapheneOS can do in the case of developers that deliberately or inadvertently write their apps to be dependent on invasive services, without also becoming dependent on those invasive services as well. 


If you experience lockups or crashes, you'll need to be able to figure out how to reproduce the behaviour reliably in order for it to be addressed, so if you can figure that out, let us know.

**Comment by LunchBoxStevieC** [comment]
With regards to the notifications, I'm aware of that.  I have the same app running on CalyxOS without MicroG installed and the notifications work for that app on that OS.  Just not on Graphene.  Just for a comparison.

**Comment by LunchBoxStevieC** [comment]
> Need to make a separate issue for each thing and please check for existing issues first.

Ok will do.  My apologies.

**Comment by thestinger** [comment]
You may need to give the app a battery optimization exception. Also, there's a major difference between notifications not working and the app's background push / polling not working so make sure to make a distinction between those.
