### ISSUE TITLE
Pixel 5 - Not all notifications working  (Unrelated to Google Services Framework)

### ISSUE THREAD

**Issue by LunchBoxStevieC** [GrapheneOS/os_issue_tracker#516]
Pixel 5 - Latest stable release flashed fresh.

Not all app notifications are working. Work around is to leave app running in background for some and others app has to be left on the screen before putting phone to sleep. Checked power settings for the app, tried reinstalling the app as well.  I know these apps are not relying on Google Services Framework because notifications work in CalyxOS without MicroG installed.

**Comment by thestinger** [comment]
It doesn't sound like notifications aren't working, but rather the apps are not properly running in the background. This is an app issue, not an OS issue. The apps need to support the appropriate APIs for running in the background and if necessary ask for a battery optimization exception. You can potentially configure the apps differently and manually grant a battery optimization exception but if they aren't written to handle device and app idle states, that's not going to work.

GrapheneOS enables the modern power management features for the OS and apps like the stock OS. Apps need to properly implement handling this. The OS you're comparing to doesn't enable that.

**Comment by thestinger** [comment]
It's an app issue so you need to report it to the app developers, or work around it by changing their settings and/or giving them a battery optimization exception. Giving them a battery optimization exception won't work if they don't use the appropriate APIs to run during idle states. There's nothing we can do about it since we're not going to be disabling using the modern power management to work around legacy / broken third party apps. Those developers need to fix their apps. It's quite important to have this the power management features enabled for battery life.

**Comment by LunchBoxStevieC** [comment]
So it works in standard Android like you would find on a Samsung.  It works on CalyxOS without MicroG installed.  It doesn't work on Graphene.  Same apps across all 3, same settings.  I've mucked around with the battery optimization settings, I've played with disabling power management etc.  Not a huge deal but an annoyance is all because my PIR wifi motion sensors on the other 2 OS will notify in the bar at the top and on-screen but not in Graphene.

**Comment by thestinger** [comment]
As I said above, GrapheneOS enables the standard power optimization features (idle states for the OS and apps) used in the stock OS. In the stock OS, apps tend to use Google servers to implement background push via FCM. On Android without Play services, they need to use their own implementation. It sounds like you're using apps with a broken implementation of that which does not support modern Android power management. Again, the other OS without Play services that you're comparing to doesn't enable the modern power management.

**Comment by LunchBoxStevieC** [comment]
I see what you are getting at now.  Sorry for misunderstanding.  Ok then, it is what it is... Not a big deal.  I appreciate the help.

**Comment by thestinger** [comment]
I recommend taking a look at https://developer.android.com/topic/performance/power/power-details. The other OS without Play services that you're comparing to isn't enabling this functionality and, they do have a semi-working implementation of FCM (via Google servers as usual of course) if that's enabled.

Apps supporting modern Android need to be written to either work within these restrictions or bypass them via a foreground service like Signal. It sounds like you're talking about apps without support for doing their work in the background on modern Android without Play services. Presumabl

**Comment by thestinger** [comment]
I recommend taking a look at https://developer.android.com/topic/performance/power/power-details. The other OS without Play services that you're comparing to isn't enabling this functionality.

Apps supporting modern Android need to be written to either work within these restrictions or bypass them via a foreground service like Signal. It sounds like you're talking about apps without support for doing their work in the background on modern Android without Play services.

It's an app issue and needs to be reported to the app developers. We can't fix an app without support for modern Android ourselves. GrapheneOS isn't going to disable the modern Android power management system. Apps like Signal and many others handle this properly. Other app developers really need to do better, and they aren't going to do better if users keep reporting the problems to us rather than them or simple stay silent about it. Report the problem to them and leave a review stating that their app doesn't provide working notifications when in the background on modern Android without Play services.

**Comment by thestinger** [comment]
So, for example, if they use alarms, but don't mark them as running while idle:


Regular alarms: Deferred to window
While-idle alarms: Deferred up to 9 minutes

Then they get substantially delayed, and it gets longer and longer between windows as the device is idle.

**Comment by thestinger** [comment]
If they simply depend on trying to keep a service running in the background without a foreground service... well... that doesn't work reliably even without these restrictions, so it wasn't working for you before reliably, just some of the time before it got killed. It sounds like the apps are simply broken. They don't actually use the proper OS APIs to run in the background, particularly while idle, which requires using `WhileIdle` variants of APIs, etc.

**Comment by LunchBoxStevieC** [comment]
After reading the explanation I totally understand and yes I'd agree the app is broken in the manner described.  I'll mention it to them and hopefully they correct it.

**Comment by thestinger** [comment]
We could probably make a toggle to dynamically turn the auto power management stuff on and off but ideally apps would have been updated by now since this started getting introduced much earlier than Android 9. It has just been tightened up over time and also made more granular to work better *without* needing to grant exceptions to apps.

So, as an exception of what the exceptions do, they let you have precise idle alarms rather than delayed for up to 9 minutes. It also allows apps to connect to the network while the device is idle. However, if the apps don't actually use the while-idle APIs or a foreground service (appears as a persistent notification that's generally silent / low priority so it's unintrusive) then the battery optimization exception does no good for them because they don't understand how to take advantage of it. We should probably make an FAQ entry with all this info.

**Comment by thestinger** [comment]
Android 6 is when Doze and App Standby got introduced, which is the feature we're enabling, but the modern incarnation of it documented at that link above.

**Comment by LunchBoxStevieC** [comment]
I never really understood the power managment nonsense anyway.  Seems to me that even when turned off (as much as possible) in various android implementations it never made much of a difference but maybe I'm the wrong use case and there is validity for having it.  I can say that the power consumption under Graphene is excellent.  Maybe because it's not calling home constantly like traditional Android?  LOL

**Comment by thestinger** [comment]
It does make a substantial difference. It's just unfortunate that many apps do not run a foreground service and/or use while-idle alarms despite it being around since Android 6. It's all part of many apps having lackluster or non-existent support for non-Play-services devices.

**Comment by LunchBoxStevieC** [comment]
sudo rm terrible_code  
sudo mk better_code

I guess!

**Comment by thestinger** [comment]
For alarms, which apps use to trigger events after a timeout or at an interval, such as polling for changes, they simply need to switch from `set` and `setExact` to `setAndAllowWhileIdle` and `setExactAndAllowWhileIdle`.

**Comment by LunchBoxStevieC** [comment]
I'll mention that in my complaint to them about their app not working in non-google services framework implementations of Android.

**Comment by thestinger** [comment]
Some app developers are really too lazy to even do that much to support non-Play-services devices.

Running a foreground service to continuously do stuff, to listen for non-passive-broadcast events or to do it at a rate quicker than alarms will allow requires running a foreground service like Signal. That allows an app like Signal to keep a process running so they can be notified of network changes (to reconnect) and to occasionally ping their connection to make sure it's still alive. That's why Signal has to run it. They push events from their server to the app, just like FCM does via Play services / Google servers. They need the foreground service to deal with network changes or the network killing their connection silently though. Ideally... connections would not be killed silently like that.

**Comment by thestinger** [comment]
It's really quite straightforward for app developers to deal with it and they just like pretending it's doom and gloom / super complicated. Mostly, app developers just don't want to run a foreground service where users can see they are actively doing something in the background.

**Comment by thestinger** [comment]
It's really quite straightforward for app developers to deal with it and they just like pretending it's doom and gloom / super complicated. Mostly, app developers complain because they don't want to run a foreground service where users can see they are actively doing something in the background.

**Comment by thestinger** [comment]
Google gives them FCM as an escape hatch and unfortunately that means app developers tend to just move to sending a huge amount of push events via FCM. Google has started cracking down on that though, and they don't allow sending a huge amount of high priority push events guaranteed to wake up the app. Ideally, the OS would have a more neutral push design where the OS gives the app information on where the push events should be submitted, and then their app server does that, rather than only going via a proprietary Google service.

**Comment by LunchBoxStevieC** [comment]
Interesting... Thanks for explaining it.
