### ISSUE TITLE
Cannot get internet data on new Pixel 4A 5G on Straighttalk new SIM

### ISSUE THREAD

**Issue by Xcutioner2021** [GrapheneOS/os_issue_tracker#529]
I just got a Pixel 4A 5G and used the Straighttalk, Bring your own Phone Sim card.  I was able to activate it and can make calls.  But I can't get to the internet, however when Wi-Fi is active, I can get to the internet.  I called Straighttalk and they said everything is working.  Can someone check the APN settings for the Pixel 4a 5G and make sure the Straighttalk service using the Verizon Sim settings are correct?

Thanks for your help.

**Comment by thestinger** [comment]
We use the same APN configuration as the stock OS. Verizon is known to be a problematic carrier depending on bloatware apps that are not included in AOSP or GrapheneOS. It's quite likely an issue on their end. I don't think there is anything for us to change.

**Comment by thestinger** [comment]
You should contact the carrier again and consider switching to a better carrier if they won't help address the problem, which is on their end.

**Comment by Xcutioner2021** [comment]
Thanks Daniel,

When they tried to help me, I was missing network settings and could not select LTE, so I wanted to confirm I didn't need to manually update the APN, but couldn't when I tried to.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by thestinger** [comment]
Verizon tends to disable configuring the APN. It's their choice.

**Comment by thestinger** [comment]
You need to ask the carrier for support. We're unable to do anything more than using the same APNs as the stock OS. Beyond that, it's not up to us. We may decide to implement ignoring the carrier disabling configuring APNs, but that's their choice, so it's their fault if the configuration isn't available. I recommend using a better carrier if you're having problems and they won't provide support. Verizon is known to be problematic, particularly some of their MVNOs. There's *very little* we can do about them depending on having proprietary bloatware apps not included in AOSP/GrapheneOS instead of following standards.

**Comment by Xcutioner2021** [comment]
Who is the best carrier to work with? Straighttalk has SIM cards for ATT/Verzon/T-Mobile.

Chris
‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by thestinger** [comment]
T-Mobile works really well. AT&T is fine. Nearly every carrier other than Verizon will fully work.

Verizon largely works but there are issues with some of their MVNOs and even the main carrier has missing features.

Sprint is horrible and by far the worst but it's a legacy carrier that's being phased out by T-Mobile since they bought it.
