### ISSUE TITLE
Loss of SIM connectivity with 21.04.05 update

### ISSUE THREAD

**Issue by SamirHafez** [GrapheneOS/os_issue_tracker#538]
Hi,

I seem to have lost all SIM connectivity (calls and mobile data) with the latest update.

From the moment I turn on my phone all I see is the message "Emergency Calls Only - EE"

I've tried other SIM cards and they're all failing to connect. I've also tried my SIM on a different phone and it connects fine.

I've checked access points and they seem accurate. I've also checked *#*#4636#*#* and compared it to a phone where things are working and I don't see any obvious differences.

Is there a way I can further debug this?

Thanks in advance.

**Comment by thestinger** [comment]
Need to know the device model and carrier.

**Comment by SamirHafez** [comment]
@thestinger sorry of course.

Pixel 4a with an EE SIM in the UK

**Comment by SamirHafez** [comment]
@thestinger also, is there a downgrade mechanism for GOS?

**Comment by Zuranium** [comment]
I have this issue also. On a pixel 4 with mint mobile.

**Comment by thestinger** [comment]
Have you changed the preferred network mode? Is it possible you enabled LTE only mode but don't have LTE at the moment?

**Comment by thestinger** [comment]
You can't easily downgrade. Doesn't work that way. The problem needs to be resolved since you need the security updates. Keep in mind we haven't gotten these reports from other people so while it's possible this carrier is broken with GrapheneOS that doesn't really seem likely.

**Comment by SamirHafez** [comment]
> Have you changed the preferred network mode? Is it possible you enabled LTE only mode... 

I haven't.

I've checked `*#*#4636#*#*` and its not set to "LTE Only". Ive tried other options but they all end up in the same situation.

>... but don't have LTE at the moment?

 I've also checked another android phone and with the same options the SIM works straightaway.

Also tried "LTE Only" on that other phone and it still connects so I know there's isn't an issue with my carrier.

Ive also check the APN configuration and they match what my alternative phone has.

> Keep in mind we haven't gotten these reports from other people so while it's possible this carrier is broken with GrapheneOS that doesn't really seem likely.

That's another thing. I don't think the carrier is broke with GOS because I've also tried a SIM from a different carrier (giffgaff) and the result was the same.

**Comment by thestinger** [comment]
LTE only is a GrapheneOS-specific option. I don't mean setting the preferred mode to LTE and below.

**Comment by thestinger** [comment]
> That's another thing. I don't think the carrier is broke with GOS because I've also tried a SIM from a different carrier (giffgaff) and the result was the same.

Can you please try the network settings reset option. Also, perhaps you disabled necessary system apps or system app permissions. The app preference reset option is worth trying too.

**Comment by thestinger** [comment]
(both of those are in the System reset options)

**Comment by SamirHafez** [comment]
> LTE only is a GrapheneOS-specific option. I don't mean setting the preferred mode to LTE and below.

I don't see this option (I wonder if I need a connection to even be presented with it)

![Screenshot_20210413-112639.png](https://user-images.githubusercontent.com/644589/114538695-8ef78b00-9c4b-11eb-9c92-a694770f86c7.png)

![Screenshot_20210413-112636.png](https://user-images.githubusercontent.com/644589/114538709-9323a880-9c4b-11eb-83db-a6e2ee43e709.png)

> Can you please try the network settings reset option. Also, perhaps you disabled necessary system apps or system app permissions. The app preference reset option is worth trying too.

Did both resets now and also restarted the phone. Same situation I'm afraid 😕

**Comment by thestinger** [comment]
You should make sure your IMEI isn't blacklisted.

**Comment by thestinger** [comment]
This is only happening for you and is happening across multiple carriers so there are essentially 3 possibilities: IMEI blacklisted, hardware failure, or the OS state is somehow screwed up. A factory reset could fully rule out the issue of it being something to do with the OS state being screwed up. However, performing the app reset and network reset already ruled out a lot of those possibilities. Haven't had any reports of similar issues from others and there's little reason to think it was caused by the OS update, especially after confirming it doesn't work with another carrier either.

You'll need to provide logs in order to say anything else about this. Going to need to consider it an issue of a blacklisted IMEI or hardware failure without more information to think otherwise. The fact that it happens on multiple carriers is a strong indication that there's nothing we can do, unfortunately.

**Comment by SamirHafez** [comment]
@thestinger so a few of the free IMEI checking services are indeed listing this phone IMEI as BLACKLISTED 😞 .

I guess i need to take this up with the store that sold me this phone as new/sealed...

Thanks anyway

**Comment by drschwabe** [comment]
Also lost cell connection after doing latest update.  
No changes made to phone or settings other than the OS update and reboot.  
Fido Canada / Pixel 3

**Comment by kalyhaezust** [comment]
Although this turned out to not be the case here, I'd like to add that the Pixel 4A is also known to have issues with the sim card slot, **unrelated to the OS running on it**.

 Some resolve the problem by putting a piece of sim-card shaped paper underneath the sim card (https://old.reddit.com/r/GooglePixel/comments/m2g6cf/no_sim_card_error_on_pixel_4a/h91hrk0/). 

I used 120g/(m^2) paper, only worked intermittently, after a couple of days, not at all. Worked up to two sheets of paper in thickness, could barely fit the sim slot and still didn't work.
