### ISSUE TITLE
RQ2A.210405.005.2021.04.16.04 Beta Test Results

### ISSUE THREAD

**Issue by southwestgit** [GrapheneOS/os_issue_tracker#546]
Beta Testing Checklist
Date: April 17, 2021
Device: 3a
Build number: RQ2A.210405.005.2021.04.16.04

Recieve incoming calls: Works
Make outgoing phone calls: Yes
Recieve incoming texts: Yes
Send outgoing texts: Yes
Internet connectivity: Yes
Internet browsing: Yes
Vanadium use:
 * Video playback: Yes
 * Renders websites: Yes
Media playback: Yes
PDF Viewer: Not Tested
Alarms/Timer: Yes
Cameras (Front and Rear): Yes
Video: Yes
Microphones: Yes
USB Devices & Peripherals: Yes
File Browsing: Yes
Media Transfer to PC: Not Tested
Application Installs: Yes
Switch Between Profiles: Yes
Log Out Profiles: Yes

Other Notes:
Phone working as expected.

**Comment by thestinger** [comment]
Thanks.

**Comment by Peter-Easton** [comment]
# Beta Testing Checklist
**Date:** April 17th, 2021
**Device:** Flame (Pixel 4)
**Build number:** RQ2A.210305.006.2021.04.16.04

**Receive incoming calls:** Not Tested
**Make outgoing phone calls:** Not Tested
**Receive incoming SMS:** Works
**Send outgoing SMS:** Works
**Receive incoming MMS:** Works
**Send outgoing MMS:** Works
**Internet connectivity:** Works
**Internet browsing:** Works
**Vanadium use**
 * Video playback: Works
 * Renders websites: Works
 * Password auto-fill: Works
 * Bookmarks: Works
**Notes:** The disabled new anti-features from upstream, including news feed do not appear on Vanadium, as expected. 

**Media playback:** Works
**Bluetooth Audio Pairing:** Works
**Bluetooth Audio Playback:** Works
**Bluetooth Audio Calling:** Works
**PDF Viewer:** Working
**Alarms:** Not Tested
**Timer:** Not Tested
**Cameras (Front and Rear):** Works
**Video:** Works (The bug in selfie video camera on OpenCamera is preexisting and caused by an upstream issue. A workaround is in place.)
**Handset Microphones:** Works
**Handset Speakers** Works
**USB Devices & Peripherals:** 
* USB Mass Storage: Works
* Keyboards: Not Tested
* USB Digital Audio Output: Works

**File Browsing:** 
**Media Transfer to PC:** Working
**Application Installs:** Not Tested
**Switch Between Profiles:** Not Tested
**Log Out Profiles:** Not Tested
**Seedvault Backups:** Works

**Other Notes:**
Everything looks good. I was under a bit more pressure for time than normal, but everything I tested seemed to work. What I didn't test is listed as "Not tested."

**Comment by Jawshy** [comment]
# Beta Testing Checklist

**Date**: 18 April 2021
**Device**: Bonito (Pixel 3a XL)
**Build number**: RQ2A.210405.005.2021.04.16.04

**Receive Incoming Calls**: ✅ Wi-Fi calling and 4G VoLTE
**Make Outgoing Phone Calls**: ✅ Wi-Fi calling and 4G VoLTE
**Receive Incoming SMS**: ✅ Wi-Fi SMS and 4G LTE
**Send Outgoing SMS**: ✅ Wi-Fi SMS and 4G LTE
**Receive Incoming MMS**: Not tested
**Send Outgoing MMS**: Not tested
**Internet Connectivity**: ✅
**Internet Browsing**: ✅
**Vanadium Use**: 
* Video Playback: ✅
* Renders Websites: ✅

**Media Playback**: ✅
**Bluetooth Audio Pairing**: Not tested
**Bluetooth Audio Playback**: Not tested
**Bluetooth Audio Calling**: Not tested
**PDF Viewer**: ✅
**Alarms**: ✅
**Timer**: ✅
**Cameras (Front and Rear)**: ✅
**Video**: ✅
**Handset Microphones**: ✅
**Handset Speakers**: ✅
**File Browsing**: ✅
**Media Transfer to PC**: ✅
**Application Installs**: ✅ Updated apps via F-Droid
**Switch Between Profiles**: ✅
**Log Out Profiles**: ✅
**Seedvault Backups**: ✅ Backed up
