### ISSUE TITLE
cannot install play services

### ISSUE THREAD

**Issue by h2dden** [GrapheneOS/os_issue_tracker#690]
I am Pixel 3, running the latest version of OS.
I have play services installed in other profiles, but when trying to update the play services to the latest version, com.google.android.gms fails to install.
Trying to understand why, I am starting with a fresh profile and try to install com.google.android.gms
It fails with the message Install_Failed_Version_Downgrade
Again, the start is with a fresh profile: nothing but the bare profile. Any other profile with working play services is turned off

**Comment by h2dden** [comment]
do you read these things before closing them?
wrf bro?
I have stated from the begining: fresh profile. Do you mean that if I install play services in one profile, I put it to sleep and then I create a fresh profile I should be able to use play services from the other profile?

Then, I am downloading the latest versions from graphene website: everytime I am trying to install these play services into a profile. I have tried ro install some old apk

**Comment by h2dden** [comment]
*I have never tried to...

**Comment by h2dden** [comment]
so, read again. I am starting with a fresh profile

**Comment by thestinger** [comment]
You aren't reading what I wrote. The answers are all there already. I fully understand what's happening.

**Comment by thestinger** [comment]
You installed an update to Play services from the Play Store.

**Comment by thestinger** [comment]
It automatically downloaded an update and showed you the update prompt for it. You updated it. That's fine, but since you updated it, you have a newer version than apps.grapheneos.org and need to get the newer version rather than the one from there. We don't have time to update that while migrating to Android 12 and we aren't going to be immediately updating it before Play Store updates are rolled out to most users. They do staggered rollouts. They don't start at 100% of users getting the update. They start at something like 25%.
