### ISSUE TITLE
investigate tethering carrier interactions and make changes to it again

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/os_issue_tracker#70]

**Comment by thestinger** [comment]
Some input from @keshto:

> On the Pixel sailfish Network & internet options the Hotspot & tethering option is disabled. If one opens the option via the quick tile and tries to enable any of the hotsport/tethering options it fails TetherProvisioningAct: Provisioning app is configured, but not available.
>
> Looks like the tether provisioning apk is missing. Alternatively, one could set the noprovisioning property to true setprop net.tethering.noprovisioning true, but that requires root.

**Comment by ryanvaughn44** [comment]
How do I make a change on the carrier AT&T? It will not allow me to add a DUN to my APN.  Good any answers to my issue?

**Comment by thestinger** [comment]
That doesn't sound like an issue but rather things working as intended for that carrier. The issue tracker is for working on features or bugs rather than providing support or answers to questions. GrapheneOS plans to make changes in this area but no one has expressed any interest in working on it, and no progress will be made until that happens. It's a very low priority.

**Comment by MadCamel** [comment]
Hi. So to make tethering work on some carriers we need the ability to add 'dun' to the apn type.

One issue is that the default apn profiles are not editable in the UI. This is probably to keep people from messing up their settings and can be left alone.

The problem arises when one tries to create a new apn profile by hand containing the 'dun' apn type.

Check out this extremely user-hostile commit: 
https://android.googlesource.com/platform/packages/apps/Settings/+/607e684f64e1bf486e9811acfae8c46ea97ed236%5E%21/

Reverting this should allow people to tether regardless of their carriers feelings about the matter.

**Comment by thestinger** [comment]
I don't think that's going to work if the carrier blocks doing it. It just won't work.

**Comment by thestinger** [comment]
I think the tethered traffic has to look like regular mobile data traffic.

**Comment by keshto** [comment]
No, that is not the case. It is on the client side. If the build.prop option I posted earlier or if the before mentioned commit were to be reverted that would do it. From the carrier side they see the traffic coming from the phone. If they did deep packet inspection or even look at the headers they could see a different user agent or desktop only application. However, if they blocked that data then "desktop mode" would not work on most mobile browsers.

**Comment by thestinger** [comment]
So is `net.tethering.provisioning=1` also required then? It's really not clear that things will work the way you're saying based on changing that. We can revert that change but setting `net.tethering.provisioning=1` is more likely to cause problems.

**Comment by keshto** [comment]
Setting `net.tethering.provisioning` to 1 oversteps asking the carrier and just allows tethering. This skips the carrier provisioning logic. The commit @MadCamel suggested allows one to edit the APN and in most cases allows one to get around the carrier as well although im not sure if it short circuts the asking the carrier logic which is the error/bug that I saw. The build prop option is not also required if you were to go that route (I didnt read the whole commit. So, double check)

The workaround I gave and what @MadCamel suggested both overstep the carrier and allow tethering even if you are not supposed to. The legit reason, which when I filed the bug, was because the tether provisioning apk was missing. That apk calls out to carrier and asks if the plan allow and if so allows the user else denys them. If that is apk is open source (I believe it is, would have to double check AOSP source, but on phone only now), adding it would be the cleanest solution that is fair to the carrier. Otherwise these other suggestions overstep the carrier.

**Comment by thestinger** [comment]
Tether provisioning seems to be part of the Settings app and seems to be included.

**Comment by thestinger** [comment]
Didn't mean to press close.

**Comment by keshto** [comment]
Last I tried was on a pixel sailfish so I dont know what has changed since then. When I was using graphene the option to enable tethering was disabled and one could not even enable hotspot. If that is no longer the case and the option is available and one can tether with an eligible plan then that would have closed the bug I opened. It would be best to work with someone that has a supported phone to pinpoint the exact problem about adding the DUN. I would be curious if Ryan or @MadCamel are having issues with a valid plan, which should not need any editing of the APN, or if they are trying to bypass the carrier.

Sorry I cant test and dont even know if latest source would build for a sailfish anymore nor do I have the time to make a one off build to try.

**Comment by thestinger** [comment]
We can't make changes without it being tested and verified to work properly without undesirable consequences. This issue was filed based on not knowing what has to be done and we can't do it based on what people assume will work.

**Comment by thestinger** [comment]
@keshto Tethering has always worked fine on GrapheneOS with carriers that support it. The attempts to work around carriers blocking / disabling / breaking it have come and gone over time. At the moment, we don't do that, and we can't do it without verifying / confirming the changes work as intended without making things worse or causing negative consequences.

**Comment by keshto** [comment]
Didnt work for me when I filed the bug. Thus why I opened it, but am glad it is working now.

As far as getting around the carrier goes, yes would have to find someone else to test. My phone is too old and even if not my plan allows tethering.

On March 14, 2021 5:15:30 AM UTC, Daniel Micay ***@***.***> wrote:
***@***.*** Tethering has always worked fine on GrapheneOS with carriers

**Comment by thestinger** [comment]
It was always working fine on at least some carriers.

**Comment by MadCamel** [comment]
It doesn't work with my carrier. If someone can make a build with either of the above modifications I would be willing to test even though it'd mean wiping my daily driver.

**Comment by thestinger** [comment]
This should be addressed for the next release via https://github.com/GrapheneOS/platform_frameworks_base/commit/d4e03e77dd590e3ed89af8b72d5c09f875fc46b0 and https://github.com/GrapheneOS/platform_build/commit/b22db418509758b781699898dc43c1c1d3a94999. Can file new issues if there are new problems caused by these changes or if they don't work for your case.
