### ISSUE TITLE
"Play Services Error" thrown when setting up Signal from APK in un-googled profile

### ISSUE THREAD

**Issue by chrisblec** [GrapheneOS/os_issue_tracker#725]
Running a fresh Graphene install on Pixel 5a.

1. Installed Graphene from barbet-factory-2021100606
2. Used Shelter to create work profile
3. Installed sandboxed GPS in work profile only
4. Created 2nd user profile just for signed-in Google
5. Installed sanboxed GPS in  2nd user profile
6. Signed into GPS in 2nd user profile
7. Downloaded Signal APK to main profile (no GPS installed)
8. After 1st open, on phone# screen, receive "Play Services Error - Google Play Servics is updating or temporarily unavailable. Please try again."

Is it possible that GPS is leaking through from the other profiles somehow and Signal is trying to access but cannot?

**Comment by thestinger** [comment]
User profiles are almost entirely isolated from each other and apps can't see the apps in other user profiles. Work profiles are a much different thing and a lot of it is under the control of the app managing them. They can make exceptions on a case-by-case basis to allow app communication and the work profile isn't fully hidden / isolated. This is just how work profiles function. It's not caused by your 2nd user profile but rather the work profile.
