### ISSUE TITLE
remove / replace draw over other apps

### ISSUE THREAD

**Issue by condor0765** [GrapheneOS/os_issue_tracker#89]
Would it be possible to some how allow android to ignore this permission especially for all NOT preinstalled apps? (i.e) this will provide some amount of security, I hope. Or am I wrong? thx

**Comment by nutts0** [comment]
Don't you have to grant this specific for the app?

**Comment by condor0765** [comment]
True.
Sorry...

**Comment by thestinger** [comment]
For the time being, I would rather leave this as an option. This is being restricted over time in the stock OS and alternatives with a better security model for picture-in-picture, etc. are being introduced.

It can be disabled in a locked down variant of the OS, but I think it would be premature to do it for the main OS. The accessibility service feature is an example of something even more powerful that I cannot simply disable due to it being so essential anyway. People are responsible for making these choices on their own devices and Auditor is a good way to verify that stuff like this isn't enabled in a way that doesn't trust the user interface or that the OS hasn't been changed, etc.
